// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: post.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Post 帖子结构
type Post struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int64                  `protobuf:"varint,1,opt,name=PostId,proto3" json:"PostId,omitempty"`          // 帖子ID
	UserId        int64                  `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`          // 用户ID
	Title         string                 `protobuf:"bytes,3,opt,name=Title,proto3" json:"Title,omitempty"`             // 标题
	Content       string                 `protobuf:"bytes,4,opt,name=Content,proto3" json:"Content,omitempty"`         // 内容
	Images        string                 `protobuf:"bytes,5,opt,name=Images,proto3" json:"Images,omitempty"`           // 图片
	Theme         string                 `protobuf:"bytes,6,opt,name=Theme,proto3" json:"Theme,omitempty"`             // 主题
	Tags          string                 `protobuf:"bytes,7,opt,name=Tags,proto3" json:"Tags,omitempty"`               // 标签
	Status        int32                  `protobuf:"varint,8,opt,name=Status,proto3" json:"Status,omitempty"`          // 状态
	CreateTime    int64                  `protobuf:"varint,9,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`  // 创建时间
	UpdateTime    int64                  `protobuf:"varint,10,opt,name=UpdateTime,proto3" json:"UpdateTime,omitempty"` // 更新时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Post) Reset() {
	*x = Post{}
	mi := &file_post_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Post) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Post) ProtoMessage() {}

func (x *Post) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Post.ProtoReflect.Descriptor instead.
func (*Post) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{0}
}

func (x *Post) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *Post) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Post) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Post) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Post) GetImages() string {
	if x != nil {
		return x.Images
	}
	return ""
}

func (x *Post) GetTheme() string {
	if x != nil {
		return x.Theme
	}
	return ""
}

func (x *Post) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

func (x *Post) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Post) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *Post) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

type PostCreateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          *Post                  `protobuf:"bytes,1,opt,name=Post,proto3" json:"Post,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostCreateReq) Reset() {
	*x = PostCreateReq{}
	mi := &file_post_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostCreateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostCreateReq) ProtoMessage() {}

func (x *PostCreateReq) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostCreateReq.ProtoReflect.Descriptor instead.
func (*PostCreateReq) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{1}
}

func (x *PostCreateReq) GetPost() *Post {
	if x != nil {
		return x.Post
	}
	return nil
}

type PostCreateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int64                  `protobuf:"varint,1,opt,name=PostId,proto3" json:"PostId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostCreateResp) Reset() {
	*x = PostCreateResp{}
	mi := &file_post_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostCreateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostCreateResp) ProtoMessage() {}

func (x *PostCreateResp) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostCreateResp.ProtoReflect.Descriptor instead.
func (*PostCreateResp) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{2}
}

func (x *PostCreateResp) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type PostDeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int64                  `protobuf:"varint,1,opt,name=PostId,proto3" json:"PostId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostDeleteReq) Reset() {
	*x = PostDeleteReq{}
	mi := &file_post_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostDeleteReq) ProtoMessage() {}

func (x *PostDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostDeleteReq.ProtoReflect.Descriptor instead.
func (*PostDeleteReq) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{3}
}

func (x *PostDeleteReq) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type PostUpdateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          *Post                  `protobuf:"bytes,1,opt,name=Post,proto3" json:"Post,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostUpdateReq) Reset() {
	*x = PostUpdateReq{}
	mi := &file_post_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostUpdateReq) ProtoMessage() {}

func (x *PostUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostUpdateReq.ProtoReflect.Descriptor instead.
func (*PostUpdateReq) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{4}
}

func (x *PostUpdateReq) GetPost() *Post {
	if x != nil {
		return x.Post
	}
	return nil
}

type PostUpdateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int64                  `protobuf:"varint,1,opt,name=PostId,proto3" json:"PostId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostUpdateResp) Reset() {
	*x = PostUpdateResp{}
	mi := &file_post_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostUpdateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostUpdateResp) ProtoMessage() {}

func (x *PostUpdateResp) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostUpdateResp.ProtoReflect.Descriptor instead.
func (*PostUpdateResp) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{5}
}

func (x *PostUpdateResp) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type PostDeleteResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostDeleteResp) Reset() {
	*x = PostDeleteResp{}
	mi := &file_post_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostDeleteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostDeleteResp) ProtoMessage() {}

func (x *PostDeleteResp) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostDeleteResp.ProtoReflect.Descriptor instead.
func (*PostDeleteResp) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{6}
}

type PostDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int64                  `protobuf:"varint,1,opt,name=PostId,proto3" json:"PostId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostDetailReq) Reset() {
	*x = PostDetailReq{}
	mi := &file_post_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostDetailReq) ProtoMessage() {}

func (x *PostDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostDetailReq.ProtoReflect.Descriptor instead.
func (*PostDetailReq) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{7}
}

func (x *PostDetailReq) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

type PostDetailResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          *Post                  `protobuf:"bytes,1,opt,name=Post,proto3" json:"Post,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostDetailResp) Reset() {
	*x = PostDetailResp{}
	mi := &file_post_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostDetailResp) ProtoMessage() {}

func (x *PostDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostDetailResp.ProtoReflect.Descriptor instead.
func (*PostDetailResp) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{8}
}

func (x *PostDetailResp) GetPost() *Post {
	if x != nil {
		return x.Post
	}
	return nil
}

type PostListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostIds       []int64                `protobuf:"varint,1,rep,packed,name=PostIds,proto3" json:"PostIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostListReq) Reset() {
	*x = PostListReq{}
	mi := &file_post_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostListReq) ProtoMessage() {}

func (x *PostListReq) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostListReq.ProtoReflect.Descriptor instead.
func (*PostListReq) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{9}
}

func (x *PostListReq) GetPostIds() []int64 {
	if x != nil {
		return x.PostIds
	}
	return nil
}

type PostListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []*Post                `protobuf:"bytes,1,rep,name=Posts,proto3" json:"Posts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostListResp) Reset() {
	*x = PostListResp{}
	mi := &file_post_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostListResp) ProtoMessage() {}

func (x *PostListResp) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostListResp.ProtoReflect.Descriptor instead.
func (*PostListResp) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{10}
}

func (x *PostListResp) GetPosts() []*Post {
	if x != nil {
		return x.Posts
	}
	return nil
}

var File_post_proto protoreflect.FileDescriptor

const file_post_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"post.proto\x12\x04post\"\x80\x02\n" +
	"\x04Post\x12\x16\n" +
	"\x06PostId\x18\x01 \x01(\x03R\x06PostId\x12\x16\n" +
	"\x06UserId\x18\x02 \x01(\x03R\x06UserId\x12\x14\n" +
	"\x05Title\x18\x03 \x01(\tR\x05Title\x12\x18\n" +
	"\aContent\x18\x04 \x01(\tR\aContent\x12\x16\n" +
	"\x06Images\x18\x05 \x01(\tR\x06Images\x12\x14\n" +
	"\x05Theme\x18\x06 \x01(\tR\x05Theme\x12\x12\n" +
	"\x04Tags\x18\a \x01(\tR\x04Tags\x12\x16\n" +
	"\x06Status\x18\b \x01(\x05R\x06Status\x12\x1e\n" +
	"\n" +
	"CreateTime\x18\t \x01(\x03R\n" +
	"CreateTime\x12\x1e\n" +
	"\n" +
	"UpdateTime\x18\n" +
	" \x01(\x03R\n" +
	"UpdateTime\"/\n" +
	"\rPostCreateReq\x12\x1e\n" +
	"\x04Post\x18\x01 \x01(\v2\n" +
	".post.PostR\x04Post\"(\n" +
	"\x0ePostCreateResp\x12\x16\n" +
	"\x06PostId\x18\x01 \x01(\x03R\x06PostId\"'\n" +
	"\rPostDeleteReq\x12\x16\n" +
	"\x06PostId\x18\x01 \x01(\x03R\x06PostId\"/\n" +
	"\rPostUpdateReq\x12\x1e\n" +
	"\x04Post\x18\x01 \x01(\v2\n" +
	".post.PostR\x04Post\"(\n" +
	"\x0ePostUpdateResp\x12\x16\n" +
	"\x06PostId\x18\x01 \x01(\x03R\x06PostId\"\x10\n" +
	"\x0ePostDeleteResp\"'\n" +
	"\rPostDetailReq\x12\x16\n" +
	"\x06PostId\x18\x01 \x01(\x03R\x06PostId\"0\n" +
	"\x0ePostDetailResp\x12\x1e\n" +
	"\x04Post\x18\x01 \x01(\v2\n" +
	".post.PostR\x04Post\"'\n" +
	"\vPostListReq\x12\x18\n" +
	"\aPostIds\x18\x01 \x03(\x03R\aPostIds\"0\n" +
	"\fPostListResp\x12 \n" +
	"\x05Posts\x18\x01 \x03(\v2\n" +
	".post.PostR\x05Posts2\xa4\x02\n" +
	"\vPostService\x127\n" +
	"\n" +
	"PostCreate\x12\x13.post.PostCreateReq\x1a\x14.post.PostCreateResp\x127\n" +
	"\n" +
	"PostDelete\x12\x13.post.PostDeleteReq\x1a\x14.post.PostDeleteResp\x127\n" +
	"\n" +
	"PostUpdate\x12\x13.post.PostUpdateReq\x1a\x14.post.PostUpdateResp\x127\n" +
	"\n" +
	"PostDetail\x12\x13.post.PostDetailReq\x1a\x14.post.PostDetailResp\x121\n" +
	"\bPostList\x12\x11.post.PostListReq\x1a\x12.post.PostListRespB\x04Z\x02./b\x06proto3"

var (
	file_post_proto_rawDescOnce sync.Once
	file_post_proto_rawDescData []byte
)

func file_post_proto_rawDescGZIP() []byte {
	file_post_proto_rawDescOnce.Do(func() {
		file_post_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_post_proto_rawDesc), len(file_post_proto_rawDesc)))
	})
	return file_post_proto_rawDescData
}

var file_post_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_post_proto_goTypes = []any{
	(*Post)(nil),           // 0: post.Post
	(*PostCreateReq)(nil),  // 1: post.PostCreateReq
	(*PostCreateResp)(nil), // 2: post.PostCreateResp
	(*PostDeleteReq)(nil),  // 3: post.PostDeleteReq
	(*PostUpdateReq)(nil),  // 4: post.PostUpdateReq
	(*PostUpdateResp)(nil), // 5: post.PostUpdateResp
	(*PostDeleteResp)(nil), // 6: post.PostDeleteResp
	(*PostDetailReq)(nil),  // 7: post.PostDetailReq
	(*PostDetailResp)(nil), // 8: post.PostDetailResp
	(*PostListReq)(nil),    // 9: post.PostListReq
	(*PostListResp)(nil),   // 10: post.PostListResp
}
var file_post_proto_depIdxs = []int32{
	0,  // 0: post.PostCreateReq.Post:type_name -> post.Post
	0,  // 1: post.PostUpdateReq.Post:type_name -> post.Post
	0,  // 2: post.PostDetailResp.Post:type_name -> post.Post
	0,  // 3: post.PostListResp.Posts:type_name -> post.Post
	1,  // 4: post.PostService.PostCreate:input_type -> post.PostCreateReq
	3,  // 5: post.PostService.PostDelete:input_type -> post.PostDeleteReq
	4,  // 6: post.PostService.PostUpdate:input_type -> post.PostUpdateReq
	7,  // 7: post.PostService.PostDetail:input_type -> post.PostDetailReq
	9,  // 8: post.PostService.PostList:input_type -> post.PostListReq
	2,  // 9: post.PostService.PostCreate:output_type -> post.PostCreateResp
	6,  // 10: post.PostService.PostDelete:output_type -> post.PostDeleteResp
	5,  // 11: post.PostService.PostUpdate:output_type -> post.PostUpdateResp
	8,  // 12: post.PostService.PostDetail:output_type -> post.PostDetailResp
	10, // 13: post.PostService.PostList:output_type -> post.PostListResp
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_post_proto_init() }
func file_post_proto_init() {
	if File_post_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_post_proto_rawDesc), len(file_post_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_post_proto_goTypes,
		DependencyIndexes: file_post_proto_depIdxs,
		MessageInfos:      file_post_proto_msgTypes,
	}.Build()
	File_post_proto = out.File
	file_post_proto_goTypes = nil
	file_post_proto_depIdxs = nil
}
