// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: ai.proto

package server

import (
	"context"

	"community/service/ai/rpc/internal/logic"
	"community/service/ai/rpc/internal/svc"
	"community/service/ai/rpc/pb"
)

type AiServer struct {
	svcCtx *svc.ServiceContext
	__.UnimplementedAiServer
}

func NewAiServer(svcCtx *svc.ServiceContext) *AiServer {
	return &AiServer{
		svcCtx: svcCtx,
	}
}

func (s *AiServer) UpsertAgent(ctx context.Context, in *__.UpsertAgentReq) (*__.UpsertAgentResp, error) {
	l := logic.NewUpsertAgentLogic(ctx, s.svcCtx)
	return l.UpsertAgent(in)
}

func (s *AiServer) RunAgent(ctx context.Context, in *__.RunAgentReq) (*__.RunAgentResp, error) {
	l := logic.NewRunAgentLogic(ctx, s.svcCtx)
	return l.RunAgent(in)
}
