// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: ai.proto

package server

import (
	"context"

	"community/service/ai/rpc/internal/logic"
	"community/service/ai/rpc/internal/svc"
	"community/service/ai/rpc/pb"
)

type AiServer struct {
	svcCtx *svc.ServiceContext
	__.UnimplementedAiServer
}

func NewAiServer(svcCtx *svc.ServiceContext) *AiServer {
	return &AiServer{
		svcCtx: svcCtx,
	}
}

func (s *AiServer) CreateAgent(ctx context.Context, in *__.CreateAgentReq) (*__.CreateAgentResp, error) {
	l := logic.NewCreateAgentLogic(ctx, s.svcCtx)
	return l.CreateAgent(in)
}

func (s *AiServer) GetAgentList(ctx context.Context, in *__.GetAgentListReq) (*__.GetAgentListResp, error) {
	l := logic.NewGetAgentListLogic(ctx, s.svcCtx)
	return l.GetAgentList(in)
}
