// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package handler

import (
	"net/http"
	"time"

	Post "community.com/service/post/api/internal/handler/Post"
	Public "community.com/service/post/api/internal/handler/Public"
	"community.com/service/post/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Middleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/post/create",
					Handler: Post.PostCreateHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/post/delete",
					Handler: Post.PostDeleteHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/post/update",
					Handler: Post.PostUpdateHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithTimeout(5000*time.Millisecond),
		rest.WithMaxBytes(10485760),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Middleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/post/detail",
					Handler: Public.PostDetailHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/post/list",
					Handler: Public.PostListHandler(serverCtx),
				},
			}...,
		),
		rest.WithTimeout(5000*time.Millisecond),
		rest.WithMaxBytes(1048576),
	)
}
