services:
  # MongoDB 服务
  mongo:
    image: mongo:7.0
    container_name: mongo-local
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    volumes:
      - ./docker-data/mongo:/data/db
    networks:
      - db-network

  # MySQL 服务
  mysql:
    image: mysql:8.0
    container_name: mysql-local
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=community
      - TZ=Asia/Shanghai
    volumes:
      - ./docker-data/mysql:/var/lib/mysql
      - ./docker-data/mysql-conf:/etc/mysql/conf.d
    networks:
      - db-network

  # Redis 服务
  redis:
    image: redis:7.2
    container_name: redis-local
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass "123456"
    volumes:
      - ./docker-data/redis:/data
    networks:
      - db-network

  # scylla
  # 节点1
  scylla-node1:
    image: scylladb/scylla:5.4
    container_name: scylla-node1
    restart: unless-stopped
    ports:
      - "9042:9042"
    volumes:
      - ./docker-data/scylla/node1:/var/lib/scylla
    networks:
      - db-network
    command: --seeds=scylla-node1 --smp 1 --memory 1G --overprovisioned 1
    environment:
      - SCYLLA_BROADCAST_ADDRESS=scylla-node1
    healthcheck:
      test: ["CMD", "cqlsh", "-u", "cassandra", "-p", "cassandra", "-e", "DESCRIBE keyspaces"]
      interval: 10s
      timeout: 10s
      retries: 30
      start_period: 60s

  scylla-node2:
    image: scylladb/scylla:5.4
    container_name: scylla-node2
    restart: unless-stopped
    ports:
      - "9043:9042"
    volumes:
      - ./docker-data/scylla/node2:/var/lib/scylla
    networks:
      - db-network
    command: --seeds=scylla-node1 --smp 1 --memory 1G --overprovisioned 1
    environment:
      - SCYLLA_BROADCAST_ADDRESS=scylla-node2
    healthcheck:
      test: ["CMD", "cqlsh", "-u", "cassandra", "-p", "cassandra", "-e", "DESCRIBE keyspaces"]
      interval: 10s
      timeout: 10s
      retries: 30
      start_period: 60s
    depends_on:
      scylla-node1:
        condition: service_healthy  # 使用健康状态依赖

  # Zookeeper 服务
  zookeeper:
    image: bitnami/zookeeper:3.9.1
    container_name: zookeeper-local
    restart: always
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - ./docker-data/zookeeper:/bitnami/zookeeper
    networks:
      - db-network

  # Kafka 服务
  kafka:
    image: bitnami/kafka:3.6.2
    container_name: kafka-local
    restart: always
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - ./docker-data/kafka:/bitnami/kafka
    networks:
      - db-network
    depends_on:
      - zookeeper

networks:
  db-network:
    driver: bridge