services:
  # MongoDB 服务
  mongo:
    image: mongo:7.0
    container_name: mongo-local
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    volumes:
      - ./docker-data/mongo:/data/db
    networks:
      - db-network

  # MySQL 服务
  mysql:
    image: mysql:8.0
    container_name: mysql-local
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=community
      - TZ=Asia/Shanghai
    volumes:
      - ./docker-data/mysql:/var/lib/mysql
      - ./docker-data/mysql-conf:/etc/mysql/conf.d
    networks:
      - db-network

  # Redis 服务
  redis:
    image: redis:7.2
    container_name: redis-local
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass "123456"
    volumes:
      - ./docker-data/redis:/data
    networks:
      - db-network

  # Scylla 服务
  scylla:
    image: scylladb/scylla:5.4
    container_name: scylla-local
    restart: always
    ports:
      - "9042:9042"
      - "9160:9160"
    volumes:
      - ./docker-data/scylla:/var/lib/scylla
    networks:
      - db-network
    command: --smp 1 --memory 1G

  # Zookeeper 服务
  zookeeper:
    image: bitnami/zookeeper:3.9.1
    container_name: zookeeper-local
    restart: always
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - ./docker-data/zookeeper:/bitnami/zookeeper
    networks:
      - db-network

  # Kafka 服务
  kafka:
    image: bitnami/kafka:3.6.2
    container_name: kafka-local
    restart: always
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - ./docker-data/kafka:/bitnami/kafka
    networks:
      - db-network
    depends_on:
      - zookeeper

networks:
  db-network:
    driver: bridge