// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package types

type WebSocketReq struct {
	ClientType string `from:"client_type"` // 连接的类型，ios等
	Version    string `from:"version"`     // 连接的版本号
}

type WebSocketResp struct {
	ConnectedId string `json:"connected_id"` // 服务器分配的连接ID
}
