// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"
	"time"

	message "community/service/message/api/internal/handler/message"
	"community/service/message/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/message/create",
				Handler: message.MessageCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/message/delete/id",
				Handler: message.MessageDeleteByIdHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/message/list",
				Handler: message.MessageListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/message/update/id",
				Handler: message.MessageUpdateByIdHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithTimeout(3000*time.Millisecond),
		rest.WithMaxBytes(1048576),
	)
}
