// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3
// Source: account.proto

package relationsservice

import (
	"context"

	"community.com/account/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Relations               = __.Relations
	User                    = __.User
	UserDeleteReq           = __.UserDeleteReq
	UserDeleteResp          = __.UserDeleteResp
	UserLoginReq            = __.UserLoginReq
	UserLoginResp           = __.UserLoginResp
	UserQueryReq            = __.UserQueryReq
	UserQueryResp           = __.UserQueryResp
	UserRegisterReq         = __.UserRegisterReq
	UserRegisterResp        = __.UserRegisterResp
	UserRelationsGetReq     = __.UserRelationsGetReq
	UserRelationsGetResp    = __.UserRelationsGetResp
	UserRelationsUpdateReq  = __.UserRelationsUpdateReq
	UserRelationsUpdateResp = __.UserRelationsUpdateResp
	UserUpdateReq           = __.UserUpdateReq
	UserUpdateResp          = __.UserUpdateResp

	RelationsService interface {
		UserRelationsUpdate(ctx context.Context, in *UserRelationsUpdateReq, opts ...grpc.CallOption) (*UserRelationsUpdateResp, error)
		UserRelationsGet(ctx context.Context, in *UserRelationsGetReq, opts ...grpc.CallOption) (*UserRelationsGetResp, error)
	}

	defaultRelationsService struct {
		cli zrpc.Client
	}
)

func NewRelationsService(cli zrpc.Client) RelationsService {
	return &defaultRelationsService{
		cli: cli,
	}
}

func (m *defaultRelationsService) UserRelationsUpdate(ctx context.Context, in *UserRelationsUpdateReq, opts ...grpc.CallOption) (*UserRelationsUpdateResp, error) {
	client := __.NewRelationsServiceClient(m.cli.Conn())
	return client.UserRelationsUpdate(ctx, in, opts...)
}

func (m *defaultRelationsService) UserRelationsGet(ctx context.Context, in *UserRelationsGetReq, opts ...grpc.CallOption) (*UserRelationsGetResp, error) {
	client := __.NewRelationsServiceClient(m.cli.Conn())
	return client.UserRelationsGet(ctx, in, opts...)
}
