// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: ai.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpsertAgentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       int64                  `protobuf:"varint,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertAgentReq) Reset() {
	*x = UpsertAgentReq{}
	mi := &file_ai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertAgentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertAgentReq) ProtoMessage() {}

func (x *UpsertAgentReq) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertAgentReq.ProtoReflect.Descriptor instead.
func (*UpsertAgentReq) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{0}
}

func (x *UpsertAgentReq) GetAgentId() int64 {
	if x != nil {
		return x.AgentId
	}
	return 0
}

type UpsertAgentResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertAgentResp) Reset() {
	*x = UpsertAgentResp{}
	mi := &file_ai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertAgentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertAgentResp) ProtoMessage() {}

func (x *UpsertAgentResp) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertAgentResp.ProtoReflect.Descriptor instead.
func (*UpsertAgentResp) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{1}
}

type RunAgentReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunAgentReq) Reset() {
	*x = RunAgentReq{}
	mi := &file_ai_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunAgentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunAgentReq) ProtoMessage() {}

func (x *RunAgentReq) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunAgentReq.ProtoReflect.Descriptor instead.
func (*RunAgentReq) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{2}
}

type RunAgentResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunAgentResp) Reset() {
	*x = RunAgentResp{}
	mi := &file_ai_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunAgentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunAgentResp) ProtoMessage() {}

func (x *RunAgentResp) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunAgentResp.ProtoReflect.Descriptor instead.
func (*RunAgentResp) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{3}
}

var File_ai_proto protoreflect.FileDescriptor

const file_ai_proto_rawDesc = "" +
	"\n" +
	"\bai.proto\x12\x02ai\"+\n" +
	"\x0eUpsertAgentReq\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\x03R\aagentId\"\x11\n" +
	"\x0fUpsertAgentResp\"\r\n" +
	"\vRunAgentReq\"\x0e\n" +
	"\fRunAgentResp2k\n" +
	"\x02Ai\x126\n" +
	"\vUpsertAgent\x12\x12.ai.UpsertAgentReq\x1a\x13.ai.UpsertAgentResp\x12-\n" +
	"\bRunAgent\x12\x0f.ai.RunAgentReq\x1a\x10.ai.RunAgentRespB\x04Z\x02./b\x06proto3"

var (
	file_ai_proto_rawDescOnce sync.Once
	file_ai_proto_rawDescData []byte
)

func file_ai_proto_rawDescGZIP() []byte {
	file_ai_proto_rawDescOnce.Do(func() {
		file_ai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_proto_rawDesc), len(file_ai_proto_rawDesc)))
	})
	return file_ai_proto_rawDescData
}

var file_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ai_proto_goTypes = []any{
	(*UpsertAgentReq)(nil),  // 0: ai.UpsertAgentReq
	(*UpsertAgentResp)(nil), // 1: ai.UpsertAgentResp
	(*RunAgentReq)(nil),     // 2: ai.RunAgentReq
	(*RunAgentResp)(nil),    // 3: ai.RunAgentResp
}
var file_ai_proto_depIdxs = []int32{
	0, // 0: ai.Ai.UpsertAgent:input_type -> ai.UpsertAgentReq
	2, // 1: ai.Ai.RunAgent:input_type -> ai.RunAgentReq
	1, // 2: ai.Ai.UpsertAgent:output_type -> ai.UpsertAgentResp
	3, // 3: ai.Ai.RunAgent:output_type -> ai.RunAgentResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ai_proto_init() }
func file_ai_proto_init() {
	if File_ai_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_proto_rawDesc), len(file_ai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_proto_goTypes,
		DependencyIndexes: file_ai_proto_depIdxs,
		MessageInfos:      file_ai_proto_msgTypes,
	}.Build()
	File_ai_proto = out.File
	file_ai_proto_goTypes = nil
	file_ai_proto_depIdxs = nil
}
