// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: ai.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Ai_CreateAgent_FullMethodName  = "/ai.Ai/CreateAgent"
	Ai_GetAgentList_FullMethodName = "/ai.Ai/GetAgentList"
)

// AiClient is the client API for Ai service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AiClient interface {
	CreateAgent(ctx context.Context, in *CreateAgentReq, opts ...grpc.CallOption) (*CreateAgentResp, error)
	GetAgentList(ctx context.Context, in *GetAgentListReq, opts ...grpc.CallOption) (*GetAgentListResp, error)
}

type aiClient struct {
	cc grpc.ClientConnInterface
}

func NewAiClient(cc grpc.ClientConnInterface) AiClient {
	return &aiClient{cc}
}

func (c *aiClient) CreateAgent(ctx context.Context, in *CreateAgentReq, opts ...grpc.CallOption) (*CreateAgentResp, error) {
	out := new(CreateAgentResp)
	err := c.cc.Invoke(ctx, Ai_CreateAgent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiClient) GetAgentList(ctx context.Context, in *GetAgentListReq, opts ...grpc.CallOption) (*GetAgentListResp, error) {
	out := new(GetAgentListResp)
	err := c.cc.Invoke(ctx, Ai_GetAgentList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AiServer is the server API for Ai service.
// All implementations must embed UnimplementedAiServer
// for forward compatibility
type AiServer interface {
	CreateAgent(context.Context, *CreateAgentReq) (*CreateAgentResp, error)
	GetAgentList(context.Context, *GetAgentListReq) (*GetAgentListResp, error)
	mustEmbedUnimplementedAiServer()
}

// UnimplementedAiServer must be embedded to have forward compatible implementations.
type UnimplementedAiServer struct {
}

func (UnimplementedAiServer) CreateAgent(context.Context, *CreateAgentReq) (*CreateAgentResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAgent not implemented")
}
func (UnimplementedAiServer) GetAgentList(context.Context, *GetAgentListReq) (*GetAgentListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAgentList not implemented")
}
func (UnimplementedAiServer) mustEmbedUnimplementedAiServer() {}

// UnsafeAiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AiServer will
// result in compilation errors.
type UnsafeAiServer interface {
	mustEmbedUnimplementedAiServer()
}

func RegisterAiServer(s grpc.ServiceRegistrar, srv AiServer) {
	s.RegisterService(&Ai_ServiceDesc, srv)
}

func _Ai_CreateAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAgentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiServer).CreateAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ai_CreateAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiServer).CreateAgent(ctx, req.(*CreateAgentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ai_GetAgentList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiServer).GetAgentList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ai_GetAgentList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiServer).GetAgentList(ctx, req.(*GetAgentListReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Ai_ServiceDesc is the grpc.ServiceDesc for Ai service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ai_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai.Ai",
	HandlerType: (*AiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAgent",
			Handler:    _Ai_CreateAgent_Handler,
		},
		{
			MethodName: "GetAgentList",
			Handler:    _Ai_GetAgentList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ai.proto",
}
