// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: account.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=Phone,proto3" json:"Phone,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=Email,proto3" json:"Email,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=Password,proto3" json:"Password,omitempty"`
	Nickname      string                 `protobuf:"bytes,5,opt,name=Nickname,proto3" json:"Nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,6,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
	Gender        string                 `protobuf:"bytes,7,opt,name=Gender,proto3" json:"Gender,omitempty"`
	BirthDate     int64                  `protobuf:"varint,8,opt,name=BirthDate,proto3" json:"BirthDate,omitempty"`
	Role          string                 `protobuf:"bytes,9,opt,name=Role,proto3" json:"Role,omitempty"`
	Status        int64                  `protobuf:"varint,10,opt,name=Status,proto3" json:"Status,omitempty"`
	CreateAt      int64                  `protobuf:"varint,11,opt,name=createAt,proto3" json:"createAt,omitempty"`
	UpdateAt      int64                  `protobuf:"varint,12,opt,name=updateAt,proto3" json:"updateAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *User) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *User) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *User) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *User) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *User) GetBirthDate() int64 {
	if x != nil {
		return x.BirthDate
	}
	return 0
}

func (x *User) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *User) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *User) GetCreateAt() int64 {
	if x != nil {
		return x.CreateAt
	}
	return 0
}

func (x *User) GetUpdateAt() int64 {
	if x != nil {
		return x.UpdateAt
	}
	return 0
}

// 用户登录请求
type UserLoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=Phone,proto3" json:"Phone,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=Password,proto3" json:"Password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLoginReq) Reset() {
	*x = UserLoginReq{}
	mi := &file_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoginReq) ProtoMessage() {}

func (x *UserLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoginReq.ProtoReflect.Descriptor instead.
func (*UserLoginReq) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{1}
}

func (x *UserLoginReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserLoginReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserLoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// 用户登录响应
type UserLoginResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLoginResp) Reset() {
	*x = UserLoginResp{}
	mi := &file_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoginResp) ProtoMessage() {}

func (x *UserLoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoginResp.ProtoReflect.Descriptor instead.
func (*UserLoginResp) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{2}
}

func (x *UserLoginResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// 用户注册请求
type UserRegisterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=Phone,proto3" json:"Phone,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=Role,proto3" json:"Role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRegisterReq) Reset() {
	*x = UserRegisterReq{}
	mi := &file_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRegisterReq) ProtoMessage() {}

func (x *UserRegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRegisterReq.ProtoReflect.Descriptor instead.
func (*UserRegisterReq) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{3}
}

func (x *UserRegisterReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserRegisterReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserRegisterReq) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

// 用户注册响应
type UserRegisterResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRegisterResp) Reset() {
	*x = UserRegisterResp{}
	mi := &file_account_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRegisterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRegisterResp) ProtoMessage() {}

func (x *UserRegisterResp) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRegisterResp.ProtoReflect.Descriptor instead.
func (*UserRegisterResp) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{4}
}

func (x *UserRegisterResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *UserRegisterResp) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 用户删除请求
type UserDeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=Phone,proto3" json:"Phone,omitempty"` // 根据手机号删除用户
	UserId        int64                  `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=Password,proto3" json:"Password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDeleteReq) Reset() {
	*x = UserDeleteReq{}
	mi := &file_account_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDeleteReq) ProtoMessage() {}

func (x *UserDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDeleteReq.ProtoReflect.Descriptor instead.
func (*UserDeleteReq) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{5}
}

func (x *UserDeleteReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserDeleteReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserDeleteReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// 用户删除响应
type UserDeleteResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDeleteResp) Reset() {
	*x = UserDeleteResp{}
	mi := &file_account_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDeleteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDeleteResp) ProtoMessage() {}

func (x *UserDeleteResp) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDeleteResp.ProtoReflect.Descriptor instead.
func (*UserDeleteResp) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{6}
}

func (x *UserDeleteResp) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// 用户更新请求
type UserUpdateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserUpdateReq) Reset() {
	*x = UserUpdateReq{}
	mi := &file_account_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUpdateReq) ProtoMessage() {}

func (x *UserUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUpdateReq.ProtoReflect.Descriptor instead.
func (*UserUpdateReq) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{7}
}

func (x *UserUpdateReq) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// 用户更新响应
type UserUpdateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserUpdateResp) Reset() {
	*x = UserUpdateResp{}
	mi := &file_account_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUpdateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUpdateResp) ProtoMessage() {}

func (x *UserUpdateResp) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUpdateResp.ProtoReflect.Descriptor instead.
func (*UserUpdateResp) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{8}
}

func (x *UserUpdateResp) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// 用户查询请求
type UserQueryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserQueryReq) Reset() {
	*x = UserQueryReq{}
	mi := &file_account_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserQueryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserQueryReq) ProtoMessage() {}

func (x *UserQueryReq) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserQueryReq.ProtoReflect.Descriptor instead.
func (*UserQueryReq) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{9}
}

func (x *UserQueryReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserQueryReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// 用户查询响应
type UserQueryResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserQueryResp) Reset() {
	*x = UserQueryResp{}
	mi := &file_account_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserQueryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserQueryResp) ProtoMessage() {}

func (x *UserQueryResp) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserQueryResp.ProtoReflect.Descriptor instead.
func (*UserQueryResp) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{10}
}

func (x *UserQueryResp) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type Relations struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RelationsId      int64                  `protobuf:"varint,1,opt,name=RelationsId,proto3" json:"RelationsId,omitempty"`
	UserId           int64                  `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	OtherId          int64                  `protobuf:"varint,3,opt,name=OtherId,proto3" json:"OtherId,omitempty"`
	RelationshipType int64                  `protobuf:"varint,4,opt,name=RelationshipType,proto3" json:"RelationshipType,omitempty"`
	CreateAt         int64                  `protobuf:"varint,5,opt,name=createAt,proto3" json:"createAt,omitempty"`
	UpdateAt         int64                  `protobuf:"varint,6,opt,name=updateAt,proto3" json:"updateAt,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Relations) Reset() {
	*x = Relations{}
	mi := &file_account_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Relations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Relations) ProtoMessage() {}

func (x *Relations) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Relations.ProtoReflect.Descriptor instead.
func (*Relations) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{11}
}

func (x *Relations) GetRelationsId() int64 {
	if x != nil {
		return x.RelationsId
	}
	return 0
}

func (x *Relations) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Relations) GetOtherId() int64 {
	if x != nil {
		return x.OtherId
	}
	return 0
}

func (x *Relations) GetRelationshipType() int64 {
	if x != nil {
		return x.RelationshipType
	}
	return 0
}

func (x *Relations) GetCreateAt() int64 {
	if x != nil {
		return x.CreateAt
	}
	return 0
}

func (x *Relations) GetUpdateAt() int64 {
	if x != nil {
		return x.UpdateAt
	}
	return 0
}

type UserRelationsUpdateReq struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           int64                  `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	OUserId          int64                  `protobuf:"varint,2,opt,name=OUserId,proto3" json:"OUserId,omitempty"`
	RelationshipType int64                  `protobuf:"varint,3,opt,name=RelationshipType,proto3" json:"RelationshipType,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UserRelationsUpdateReq) Reset() {
	*x = UserRelationsUpdateReq{}
	mi := &file_account_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRelationsUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRelationsUpdateReq) ProtoMessage() {}

func (x *UserRelationsUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRelationsUpdateReq.ProtoReflect.Descriptor instead.
func (*UserRelationsUpdateReq) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{12}
}

func (x *UserRelationsUpdateReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserRelationsUpdateReq) GetOUserId() int64 {
	if x != nil {
		return x.OUserId
	}
	return 0
}

func (x *UserRelationsUpdateReq) GetRelationshipType() int64 {
	if x != nil {
		return x.RelationshipType
	}
	return 0
}

type UserRelationsUpdateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Relations     *Relations             `protobuf:"bytes,1,opt,name=Relations,proto3" json:"Relations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRelationsUpdateResp) Reset() {
	*x = UserRelationsUpdateResp{}
	mi := &file_account_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRelationsUpdateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRelationsUpdateResp) ProtoMessage() {}

func (x *UserRelationsUpdateResp) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRelationsUpdateResp.ProtoReflect.Descriptor instead.
func (*UserRelationsUpdateResp) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{13}
}

func (x *UserRelationsUpdateResp) GetRelations() *Relations {
	if x != nil {
		return x.Relations
	}
	return nil
}

type UserRelationsGetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	OUserId       int64                  `protobuf:"varint,2,opt,name=OUserId,proto3" json:"OUserId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRelationsGetReq) Reset() {
	*x = UserRelationsGetReq{}
	mi := &file_account_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRelationsGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRelationsGetReq) ProtoMessage() {}

func (x *UserRelationsGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRelationsGetReq.ProtoReflect.Descriptor instead.
func (*UserRelationsGetReq) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{14}
}

func (x *UserRelationsGetReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserRelationsGetReq) GetOUserId() int64 {
	if x != nil {
		return x.OUserId
	}
	return 0
}

type UserRelationsGetResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Relations     *Relations             `protobuf:"bytes,1,opt,name=Relations,proto3" json:"Relations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRelationsGetResp) Reset() {
	*x = UserRelationsGetResp{}
	mi := &file_account_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRelationsGetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRelationsGetResp) ProtoMessage() {}

func (x *UserRelationsGetResp) ProtoReflect() protoreflect.Message {
	mi := &file_account_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRelationsGetResp.ProtoReflect.Descriptor instead.
func (*UserRelationsGetResp) Descriptor() ([]byte, []int) {
	return file_account_proto_rawDescGZIP(), []int{15}
}

func (x *UserRelationsGetResp) GetRelations() *Relations {
	if x != nil {
		return x.Relations
	}
	return nil
}

var File_account_proto protoreflect.FileDescriptor

const file_account_proto_rawDesc = "" +
	"\n" +
	"\raccount.proto\x12\aaccount\"\xb4\x02\n" +
	"\x04User\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x03R\x06UserId\x12\x14\n" +
	"\x05Phone\x18\x02 \x01(\tR\x05Phone\x12\x14\n" +
	"\x05Email\x18\x03 \x01(\tR\x05Email\x12\x1a\n" +
	"\bPassword\x18\x04 \x01(\tR\bPassword\x12\x1a\n" +
	"\bNickname\x18\x05 \x01(\tR\bNickname\x12\x16\n" +
	"\x06Avatar\x18\x06 \x01(\tR\x06Avatar\x12\x16\n" +
	"\x06Gender\x18\a \x01(\tR\x06Gender\x12\x1c\n" +
	"\tBirthDate\x18\b \x01(\x03R\tBirthDate\x12\x12\n" +
	"\x04Role\x18\t \x01(\tR\x04Role\x12\x16\n" +
	"\x06Status\x18\n" +
	" \x01(\x03R\x06Status\x12\x1a\n" +
	"\bcreateAt\x18\v \x01(\x03R\bcreateAt\x12\x1a\n" +
	"\bupdateAt\x18\f \x01(\x03R\bupdateAt\"X\n" +
	"\fUserLoginReq\x12\x14\n" +
	"\x05Phone\x18\x01 \x01(\tR\x05Phone\x12\x16\n" +
	"\x06UserId\x18\x02 \x01(\x03R\x06UserId\x12\x1a\n" +
	"\bPassword\x18\x03 \x01(\tR\bPassword\"%\n" +
	"\rUserLoginResp\x12\x14\n" +
	"\x05Token\x18\x01 \x01(\tR\x05Token\"W\n" +
	"\x0fUserRegisterReq\x12\x14\n" +
	"\x05Phone\x18\x01 \x01(\tR\x05Phone\x12\x1a\n" +
	"\bPassword\x18\x02 \x01(\tR\bPassword\x12\x12\n" +
	"\x04Role\x18\x03 \x01(\tR\x04Role\"@\n" +
	"\x10UserRegisterResp\x12\x14\n" +
	"\x05Token\x18\x01 \x01(\tR\x05Token\x12\x16\n" +
	"\x06UserId\x18\x02 \x01(\x03R\x06UserId\"Y\n" +
	"\rUserDeleteReq\x12\x14\n" +
	"\x05Phone\x18\x01 \x01(\tR\x05Phone\x12\x16\n" +
	"\x06UserId\x18\x02 \x01(\x03R\x06UserId\x12\x1a\n" +
	"\bPassword\x18\x03 \x01(\tR\bPassword\"3\n" +
	"\x0eUserDeleteResp\x12!\n" +
	"\x04User\x18\x01 \x01(\v2\r.account.UserR\x04User\"2\n" +
	"\rUserUpdateReq\x12!\n" +
	"\x04User\x18\x01 \x01(\v2\r.account.UserR\x04User\"3\n" +
	"\x0eUserUpdateResp\x12!\n" +
	"\x04User\x18\x01 \x01(\v2\r.account.UserR\x04User\":\n" +
	"\fUserQueryReq\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x03R\x06UserId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"2\n" +
	"\rUserQueryResp\x12!\n" +
	"\x04User\x18\x01 \x01(\v2\r.account.UserR\x04User\"\xc3\x01\n" +
	"\tRelations\x12 \n" +
	"\vRelationsId\x18\x01 \x01(\x03R\vRelationsId\x12\x16\n" +
	"\x06UserId\x18\x02 \x01(\x03R\x06UserId\x12\x18\n" +
	"\aOtherId\x18\x03 \x01(\x03R\aOtherId\x12*\n" +
	"\x10RelationshipType\x18\x04 \x01(\x03R\x10RelationshipType\x12\x1a\n" +
	"\bcreateAt\x18\x05 \x01(\x03R\bcreateAt\x12\x1a\n" +
	"\bupdateAt\x18\x06 \x01(\x03R\bupdateAt\"v\n" +
	"\x16UserRelationsUpdateReq\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x03R\x06UserId\x12\x18\n" +
	"\aOUserId\x18\x02 \x01(\x03R\aOUserId\x12*\n" +
	"\x10RelationshipType\x18\x03 \x01(\x03R\x10RelationshipType\"K\n" +
	"\x17UserRelationsUpdateResp\x120\n" +
	"\tRelations\x18\x01 \x01(\v2\x12.account.RelationsR\tRelations\"G\n" +
	"\x13UserRelationsGetReq\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x03R\x06UserId\x12\x18\n" +
	"\aOUserId\x18\x02 \x01(\x03R\aOUserId\"H\n" +
	"\x14UserRelationsGetResp\x120\n" +
	"\tRelations\x18\x01 \x01(\v2\x12.account.RelationsR\tRelations2\xc8\x02\n" +
	"\vUserService\x12:\n" +
	"\tUserLogin\x12\x15.account.UserLoginReq\x1a\x16.account.UserLoginResp\x12C\n" +
	"\fUserRegister\x12\x18.account.UserRegisterReq\x1a\x19.account.UserRegisterResp\x12=\n" +
	"\n" +
	"UserDelete\x12\x16.account.UserDeleteReq\x1a\x17.account.UserDeleteResp\x12=\n" +
	"\n" +
	"UserUpdate\x12\x16.account.UserUpdateReq\x1a\x17.account.UserUpdateResp\x12:\n" +
	"\tUserQuery\x12\x15.account.UserQueryReq\x1a\x16.account.UserQueryResp2\xbd\x01\n" +
	"\x10RelationsService\x12X\n" +
	"\x13UserRelationsUpdate\x12\x1f.account.UserRelationsUpdateReq\x1a .account.UserRelationsUpdateResp\x12O\n" +
	"\x10UserRelationsGet\x12\x1c.account.UserRelationsGetReq\x1a\x1d.account.UserRelationsGetRespB\x04Z\x02./b\x06proto3"

var (
	file_account_proto_rawDescOnce sync.Once
	file_account_proto_rawDescData []byte
)

func file_account_proto_rawDescGZIP() []byte {
	file_account_proto_rawDescOnce.Do(func() {
		file_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_proto_rawDesc), len(file_account_proto_rawDesc)))
	})
	return file_account_proto_rawDescData
}

var file_account_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_account_proto_goTypes = []any{
	(*User)(nil),                    // 0: account.User
	(*UserLoginReq)(nil),            // 1: account.UserLoginReq
	(*UserLoginResp)(nil),           // 2: account.UserLoginResp
	(*UserRegisterReq)(nil),         // 3: account.UserRegisterReq
	(*UserRegisterResp)(nil),        // 4: account.UserRegisterResp
	(*UserDeleteReq)(nil),           // 5: account.UserDeleteReq
	(*UserDeleteResp)(nil),          // 6: account.UserDeleteResp
	(*UserUpdateReq)(nil),           // 7: account.UserUpdateReq
	(*UserUpdateResp)(nil),          // 8: account.UserUpdateResp
	(*UserQueryReq)(nil),            // 9: account.UserQueryReq
	(*UserQueryResp)(nil),           // 10: account.UserQueryResp
	(*Relations)(nil),               // 11: account.Relations
	(*UserRelationsUpdateReq)(nil),  // 12: account.UserRelationsUpdateReq
	(*UserRelationsUpdateResp)(nil), // 13: account.UserRelationsUpdateResp
	(*UserRelationsGetReq)(nil),     // 14: account.UserRelationsGetReq
	(*UserRelationsGetResp)(nil),    // 15: account.UserRelationsGetResp
}
var file_account_proto_depIdxs = []int32{
	0,  // 0: account.UserDeleteResp.User:type_name -> account.User
	0,  // 1: account.UserUpdateReq.User:type_name -> account.User
	0,  // 2: account.UserUpdateResp.User:type_name -> account.User
	0,  // 3: account.UserQueryResp.User:type_name -> account.User
	11, // 4: account.UserRelationsUpdateResp.Relations:type_name -> account.Relations
	11, // 5: account.UserRelationsGetResp.Relations:type_name -> account.Relations
	1,  // 6: account.UserService.UserLogin:input_type -> account.UserLoginReq
	3,  // 7: account.UserService.UserRegister:input_type -> account.UserRegisterReq
	5,  // 8: account.UserService.UserDelete:input_type -> account.UserDeleteReq
	7,  // 9: account.UserService.UserUpdate:input_type -> account.UserUpdateReq
	9,  // 10: account.UserService.UserQuery:input_type -> account.UserQueryReq
	12, // 11: account.RelationsService.UserRelationsUpdate:input_type -> account.UserRelationsUpdateReq
	14, // 12: account.RelationsService.UserRelationsGet:input_type -> account.UserRelationsGetReq
	2,  // 13: account.UserService.UserLogin:output_type -> account.UserLoginResp
	4,  // 14: account.UserService.UserRegister:output_type -> account.UserRegisterResp
	6,  // 15: account.UserService.UserDelete:output_type -> account.UserDeleteResp
	8,  // 16: account.UserService.UserUpdate:output_type -> account.UserUpdateResp
	10, // 17: account.UserService.UserQuery:output_type -> account.UserQueryResp
	13, // 18: account.RelationsService.UserRelationsUpdate:output_type -> account.UserRelationsUpdateResp
	15, // 19: account.RelationsService.UserRelationsGet:output_type -> account.UserRelationsGetResp
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_account_proto_init() }
func file_account_proto_init() {
	if File_account_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_proto_rawDesc), len(file_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_account_proto_goTypes,
		DependencyIndexes: file_account_proto_depIdxs,
		MessageInfos:      file_account_proto_msgTypes,
	}.Build()
	File_account_proto = out.File
	file_account_proto_goTypes = nil
	file_account_proto_depIdxs = nil
}
