// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type UserRelationsGetReq struct {
	UserId  int64 `json:"user_id"`
	OUserId int64 `json:"o_user_id"`
}

type UserRelationsGetResp struct {
	Relations Relations `json:"relations"`
}

type UserRelationsUpdateReq struct {
	UserId           int64 `json:"user_id"`
	OUserId          int64 `json:"o_user_id"`
	RelationshipType int64 `json:"relations"`
}

type UserRelationsUpdateResp struct {
	Relations Relations `json:"relations"`
}
