// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type Relations struct {
	RelationsId      int64 `json:"relations_id"`
	UserId           int64 `json:"user_id"`
	OtherId          int64 `json:"other_id"`
	RelationshipType int64 `json:"relationship_type"`
}

type UserBase struct {
	UserId    int64  `json:"user_id"`
	NickName  string `json:"nick_name"`
	Avatar    string `json:"avatar"`
	Gender    string `json:"gender"`
	BirthDate int64  `json:"birthdate"`
}

type UserInfo struct {
	UserBase    UserBase    `json:"user_base"`
	UserPrivate UserPrivate `json:"user_private"`
}

type UserPrivate struct {
	UserId   int64  `json:"user_id"`
	Phone    string `json:"phone"`
	Email    string `json:"email"`
	Password string `json:"password"`
	Role     string `json:"role"`
	Status   int64  `json:"status"`
}
