// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type UserDeleteReq struct {
	Phone    string `json:"phone"` // 根据手机号删除用户
	UserId   int64  `json:"user_id"`
	Password string `json:"password"`
}

type UserDeleteResp struct {
}

type UserLoginReq struct {
	Phone    string `json:"phone"`
	UserId   int64  `json:"userId"`
	Password string `json:"password"`
}

type UserLoginResp struct {
	Token string `json:"token"`
}

type UserQueryReq struct {
	QueryUserId int64  `json:"query_user_id"`
	Type        string `json:"type"`
}

type UserQueryResp struct {
	User UserInfo `json:"user_info"`
}

type UserRegisterReq struct {
	Phone    string `json:"phone"`
	Password string `json:"password"`
	Role     string `json:"role"`
}

type UserRegisterResp struct {
	UserId int64  `json:"user_id"`
	Token  string `json:"token"`
}

type UserUpdateReq struct {
	User UserBase `json:"user_base"`
}

type UserUpdateResp struct {
}
