// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: websocketpush.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WebSocketPushData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NotifyType    string                 `protobuf:"bytes,1,opt,name=notify_type,json=notifyType,proto3" json:"notify_type,omitempty"` // 通知的类型
	NotifyVal     string                 `protobuf:"bytes,2,opt,name=notify_val,json=notifyVal,proto3" json:"notify_val,omitempty"`    // 通知的数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebSocketPushData) Reset() {
	*x = WebSocketPushData{}
	mi := &file_websocketpush_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebSocketPushData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSocketPushData) ProtoMessage() {}

func (x *WebSocketPushData) ProtoReflect() protoreflect.Message {
	mi := &file_websocketpush_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSocketPushData.ProtoReflect.Descriptor instead.
func (*WebSocketPushData) Descriptor() ([]byte, []int) {
	return file_websocketpush_proto_rawDescGZIP(), []int{0}
}

func (x *WebSocketPushData) GetNotifyType() string {
	if x != nil {
		return x.NotifyType
	}
	return ""
}

func (x *WebSocketPushData) GetNotifyVal() string {
	if x != nil {
		return x.NotifyVal
	}
	return ""
}

type WebSocketPushReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConnId        []int64                `protobuf:"varint,1,rep,packed,name=conn_id,json=connId,proto3" json:"conn_id,omitempty"` // 通知的连接id
	PushData      *WebSocketPushData     `protobuf:"bytes,2,opt,name=push_data,json=pushData,proto3" json:"push_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebSocketPushReq) Reset() {
	*x = WebSocketPushReq{}
	mi := &file_websocketpush_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebSocketPushReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSocketPushReq) ProtoMessage() {}

func (x *WebSocketPushReq) ProtoReflect() protoreflect.Message {
	mi := &file_websocketpush_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSocketPushReq.ProtoReflect.Descriptor instead.
func (*WebSocketPushReq) Descriptor() ([]byte, []int) {
	return file_websocketpush_proto_rawDescGZIP(), []int{1}
}

func (x *WebSocketPushReq) GetConnId() []int64 {
	if x != nil {
		return x.ConnId
	}
	return nil
}

func (x *WebSocketPushReq) GetPushData() *WebSocketPushData {
	if x != nil {
		return x.PushData
	}
	return nil
}

type WebSocketPushResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebSocketPushResp) Reset() {
	*x = WebSocketPushResp{}
	mi := &file_websocketpush_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebSocketPushResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSocketPushResp) ProtoMessage() {}

func (x *WebSocketPushResp) ProtoReflect() protoreflect.Message {
	mi := &file_websocketpush_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSocketPushResp.ProtoReflect.Descriptor instead.
func (*WebSocketPushResp) Descriptor() ([]byte, []int) {
	return file_websocketpush_proto_rawDescGZIP(), []int{2}
}

var File_websocketpush_proto protoreflect.FileDescriptor

const file_websocketpush_proto_rawDesc = "" +
	"\n" +
	"\x13websocketpush.proto\x12\rwebsocketPush\"S\n" +
	"\x11WebSocketPushData\x12\x1f\n" +
	"\vnotify_type\x18\x01 \x01(\tR\n" +
	"notifyType\x12\x1d\n" +
	"\n" +
	"notify_val\x18\x02 \x01(\tR\tnotifyVal\"j\n" +
	"\x10WebSocketPushReq\x12\x17\n" +
	"\aconn_id\x18\x01 \x03(\x03R\x06connId\x12=\n" +
	"\tpush_data\x18\x02 \x01(\v2 .websocketPush.WebSocketPushDataR\bpushData\"\x13\n" +
	"\x11WebSocketPushResp2c\n" +
	"\rWebsocketPush\x12R\n" +
	"\rWebSocketPush\x12\x1f.websocketPush.WebSocketPushReq\x1a .websocketPush.WebSocketPushRespB\x04Z\x02./b\x06proto3"

var (
	file_websocketpush_proto_rawDescOnce sync.Once
	file_websocketpush_proto_rawDescData []byte
)

func file_websocketpush_proto_rawDescGZIP() []byte {
	file_websocketpush_proto_rawDescOnce.Do(func() {
		file_websocketpush_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_websocketpush_proto_rawDesc), len(file_websocketpush_proto_rawDesc)))
	})
	return file_websocketpush_proto_rawDescData
}

var file_websocketpush_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_websocketpush_proto_goTypes = []any{
	(*WebSocketPushData)(nil), // 0: websocketPush.WebSocketPushData
	(*WebSocketPushReq)(nil),  // 1: websocketPush.WebSocketPushReq
	(*WebSocketPushResp)(nil), // 2: websocketPush.WebSocketPushResp
}
var file_websocketpush_proto_depIdxs = []int32{
	0, // 0: websocketPush.WebSocketPushReq.push_data:type_name -> websocketPush.WebSocketPushData
	1, // 1: websocketPush.WebsocketPush.WebSocketPush:input_type -> websocketPush.WebSocketPushReq
	2, // 2: websocketPush.WebsocketPush.WebSocketPush:output_type -> websocketPush.WebSocketPushResp
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_websocketpush_proto_init() }
func file_websocketpush_proto_init() {
	if File_websocketpush_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_websocketpush_proto_rawDesc), len(file_websocketpush_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_websocketpush_proto_goTypes,
		DependencyIndexes: file_websocketpush_proto_depIdxs,
		MessageInfos:      file_websocketpush_proto_msgTypes,
	}.Build()
	File_websocketpush_proto = out.File
	file_websocketpush_proto_goTypes = nil
	file_websocketpush_proto_depIdxs = nil
}
