// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package handler

import (
	"net/http"
	"time"

	websocket "community/service/websocket/api/internal/handler/websocket"
	"community/service/websocket/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/websocket/client",
				Handler: websocket.WebSocketClientHandler(serverCtx),
			},
		},
		// rest.WithJwt(serverCtx.Config.Auth.AccessSecret),// 临时测试修改 todo
		rest.WithTimeout(3000*time.Millisecond),
		rest.WithMaxBytes(1048576),
	)
}
