// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: weather.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 天气增加关注城市请求
type WeatherAddDataReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserName       string                 `protobuf:"bytes,1,opt,name=UserName,proto3" json:"UserName,omitempty"`
	OpenId         string                 `protobuf:"bytes,2,opt,name=OpenId,proto3" json:"OpenId,omitempty"`
	UserId         string                 `protobuf:"bytes,3,opt,name=UserId,proto3" json:"UserId,omitempty"`
	City           string                 `protobuf:"bytes,4,opt,name=City,proto3" json:"City,omitempty"`
	Time           string                 `protobuf:"bytes,5,opt,name=Time,proto3" json:"Time,omitempty"`
	MaxTemperature string                 `protobuf:"bytes,6,opt,name=MaxTemperature,proto3" json:"MaxTemperature,omitempty"`
	MinTemperature string                 `protobuf:"bytes,7,opt,name=MinTemperature,proto3" json:"MinTemperature,omitempty"`
	Weather        []string               `protobuf:"bytes,8,rep,name=Weather,proto3" json:"Weather,omitempty"`
	Status         int64                  `protobuf:"varint,9,opt,name=Status,proto3" json:"Status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WeatherAddDataReq) Reset() {
	*x = WeatherAddDataReq{}
	mi := &file_weather_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeatherAddDataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeatherAddDataReq) ProtoMessage() {}

func (x *WeatherAddDataReq) ProtoReflect() protoreflect.Message {
	mi := &file_weather_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeatherAddDataReq.ProtoReflect.Descriptor instead.
func (*WeatherAddDataReq) Descriptor() ([]byte, []int) {
	return file_weather_proto_rawDescGZIP(), []int{0}
}

func (x *WeatherAddDataReq) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *WeatherAddDataReq) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *WeatherAddDataReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *WeatherAddDataReq) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *WeatherAddDataReq) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *WeatherAddDataReq) GetMaxTemperature() string {
	if x != nil {
		return x.MaxTemperature
	}
	return ""
}

func (x *WeatherAddDataReq) GetMinTemperature() string {
	if x != nil {
		return x.MinTemperature
	}
	return ""
}

func (x *WeatherAddDataReq) GetWeather() []string {
	if x != nil {
		return x.Weather
	}
	return nil
}

func (x *WeatherAddDataReq) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 天气增加关注城市响应
type WeatherAddDataResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeatherAddDataResp) Reset() {
	*x = WeatherAddDataResp{}
	mi := &file_weather_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeatherAddDataResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeatherAddDataResp) ProtoMessage() {}

func (x *WeatherAddDataResp) ProtoReflect() protoreflect.Message {
	mi := &file_weather_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeatherAddDataResp.ProtoReflect.Descriptor instead.
func (*WeatherAddDataResp) Descriptor() ([]byte, []int) {
	return file_weather_proto_rawDescGZIP(), []int{1}
}

var File_weather_proto protoreflect.FileDescriptor

const file_weather_proto_rawDesc = "" +
	"\n" +
	"\rweather.proto\x12\aweather\"\x89\x02\n" +
	"\x11WeatherAddDataReq\x12\x1a\n" +
	"\bUserName\x18\x01 \x01(\tR\bUserName\x12\x16\n" +
	"\x06OpenId\x18\x02 \x01(\tR\x06OpenId\x12\x16\n" +
	"\x06UserId\x18\x03 \x01(\tR\x06UserId\x12\x12\n" +
	"\x04City\x18\x04 \x01(\tR\x04City\x12\x12\n" +
	"\x04Time\x18\x05 \x01(\tR\x04Time\x12&\n" +
	"\x0eMaxTemperature\x18\x06 \x01(\tR\x0eMaxTemperature\x12&\n" +
	"\x0eMinTemperature\x18\a \x01(\tR\x0eMinTemperature\x12\x18\n" +
	"\aWeather\x18\b \x03(\tR\aWeather\x12\x16\n" +
	"\x06Status\x18\t \x01(\x03R\x06Status\"\x14\n" +
	"\x12WeatherAddDataResp2[\n" +
	"\x0eWeatherService\x12I\n" +
	"\x0eWeatherAddData\x12\x1a.weather.WeatherAddDataReq\x1a\x1b.weather.WeatherAddDataRespB\x04Z\x02./b\x06proto3"

var (
	file_weather_proto_rawDescOnce sync.Once
	file_weather_proto_rawDescData []byte
)

func file_weather_proto_rawDescGZIP() []byte {
	file_weather_proto_rawDescOnce.Do(func() {
		file_weather_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_weather_proto_rawDesc), len(file_weather_proto_rawDesc)))
	})
	return file_weather_proto_rawDescData
}

var file_weather_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_weather_proto_goTypes = []any{
	(*WeatherAddDataReq)(nil),  // 0: weather.WeatherAddDataReq
	(*WeatherAddDataResp)(nil), // 1: weather.WeatherAddDataResp
}
var file_weather_proto_depIdxs = []int32{
	0, // 0: weather.WeatherService.WeatherAddData:input_type -> weather.WeatherAddDataReq
	1, // 1: weather.WeatherService.WeatherAddData:output_type -> weather.WeatherAddDataResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_weather_proto_init() }
func file_weather_proto_init() {
	if File_weather_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_weather_proto_rawDesc), len(file_weather_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_weather_proto_goTypes,
		DependencyIndexes: file_weather_proto_depIdxs,
		MessageInfos:      file_weather_proto_msgTypes,
	}.Build()
	File_weather_proto = out.File
	file_weather_proto_goTypes = nil
	file_weather_proto_depIdxs = nil
}
