// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: websocketpush.proto

package server

import (
	"context"

	"community/service/websocketpush/rpc/internal/logic"
	"community/service/websocketpush/rpc/internal/svc"
	"community/service/websocketpush/rpc/pb"
)

type WebsocketPushServer struct {
	svcCtx *svc.ServiceContext
	__.UnimplementedWebsocketPushServer
}

func NewWebsocketPushServer(svcCtx *svc.ServiceContext) *WebsocketPushServer {
	return &WebsocketPushServer{
		svcCtx: svcCtx,
	}
}

func (s *WebsocketPushServer) WebSocketPush(ctx context.Context, in *__.WebSocketPushReq) (*__.WebSocketPushResp, error) {
	l := logic.NewWebSocketPushLogic(ctx, s.svcCtx)
	return l.WebSocketPush(in)
}
