// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package model

import (
	"context"
	"time"

	"github.com/zeromicro/go-zero/core/stores/mon"
	"go.mongodb.org/mongo-driver/mongo"
	"go.mongodb.org/mongo-driver/v2/bson"
)

type agentModel interface {
	Insert(ctx context.Context, data *Agent) error
	FindOne(ctx context.Context, id string) (*Agent, error)
	Update(ctx context.Context, data *Agent) (*mongo.UpdateResult, error)
	Delete(ctx context.Context, id string) (int64, error)
}

type defaultAgentModel struct {
	conn *mon.Model
}

func newDefaultAgentModel(conn *mon.Model) *defaultAgentModel {
	return &defaultAgentModel{conn: conn}
}

func (m *defaultAgentModel) Insert(ctx context.Context, data *Agent) error {
	if data.ID.IsZero() {
		data.ID = bson.NewObjectID()
		data.CreateTime = time.Now().Unix()
		data.UpdateTime = time.Now().Unix()
	}

	_, err := m.conn.InsertOne(ctx, data)
	return err
}

func (m *defaultAgentModel) FindOne(ctx context.Context, id string) (*Agent, error) {
	oid, err := bson.ObjectIDFromHex(id)
	if err != nil {
		return nil, ErrInvalidObjectId
	}

	var data Agent

	err = m.conn.FindOne(ctx, &data, bson.M{"_id": oid})
	switch err {
	case nil:
		return &data, nil
	case mon.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAgentModel) Update(ctx context.Context, data *Agent) (*mongo.UpdateResult, error) {
	data.UpdateTime = time.Now().Unix()

	res, err := m.conn.UpdateOne(ctx, bson.M{"_id": data.ID}, bson.M{"$set": data})
	return res, err
}

func (m *defaultAgentModel) Delete(ctx context.Context, id string) (int64, error) {
	oid, err := bson.ObjectIDFromHex(id)
	if err != nil {
		return 0, ErrInvalidObjectId
	}

	res, err := m.conn.DeleteOne(ctx, bson.M{"_id": oid})
	return res, err
}
