// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package types

type MessageContent struct {
	Text        string `json:"text"`
	MessageType int64  `json:"message_type"`
	Addition    string `json:"addition"`
}

type MessageCreateReq struct {
	SessionId string         `json:"session_id"`
	SendId    int64          `json:"send_id"`
	ReplyId   int64          `json:"reply_id"`
	Status    int64          `json:"status"`
	Content   MessageContent `json:"content"`
}

type MessageCreateResp struct {
}

type MessageDeleteByIdReq struct {
	SessionId string `json:"session_id"`
	SendId    int64  `json:"send_id"`
	MessageId int64  `json:"message_id"`
}

type MessageDeleteByIdResp struct {
}

type MessageDetail struct {
	MessageId  int64          `json:"message_id"`
	SessionId  string         `json:"session_id"`
	SendId     int64          `json:"send_id"`
	ReplyId    int64          `json:"reply_id"`
	CreateTime int64          `json:"create_time"`
	UpdateTime int64          `json:"update_time"`
	Status     int64          `json:"status"`
	Content    MessageContent `json:"content"`
}

type MessageListReq struct {
	SessionId string `json:"session_id"`
	Req       int64  `json:"req"`
	Limit     int64  `json:"limit"`
}

type MessageListResp struct {
	MessageDetails []MessageDetail `json:"message_details"`
}

type MessageUpdateByIdReq struct {
	MessageDetail MessageDetail `json:"message_detail"`
}

type MessageUpdateByIdResp struct {
}
