// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package types

type MessageContent struct {
	Text        string `json:"text"`
	MessageType int64  `json:"message_type"`
	Addition    string `json:"addition"`
}

type MessageCreateReq struct {
	SessionId string         `json:"sessionIds"`
	SendId    int64          `json:"sendId"`
	ReplyId   int64          `json:"replyId"`
	Status    int64          `json:"status"`
	Content   MessageContent `json:"content"`
}

type MessageCreateResp struct {
}

type MessageDeleteByIdReq struct {
	SessionId string `json:"sessionId"`
	SendId    int64  `json:"sendId"`
	MessageId int64  `json:"messageId"`
}

type MessageDeleteByIdResp struct {
}

type MessageDetail struct {
	MessageId  int64          `json:"messageId"`
	SessionId  string         `json:"sessionIds"`
	SendId     int64          `json:"sendId"`
	ReplyId    int64          `json:"replyId"`
	CreateTime int64          `json:"createTime"`
	UpdateTime int64          `json:"updateTime"`
	Status     int64          `json:"status"`
	Content    MessageContent `json:"content"`
}

type MessageListReq struct {
	SessionId string `json:"sessionId"`
	Req       int64  `json:"req"`
	Limit     int64  `json:"limit"`
}

type MessageListResp struct {
	MessageDetails []MessageDetail `json:"messageDetails"`
}

type MessageUpdateByIdReq struct {
	MessageDateil MessageDetail `json:"messageDateil"`
}

type MessageUpdateByIdResp struct {
}
