// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3
// Source: account.proto

package server

import (
	"context"

	"community.com/account/rpc/internal/logic/relationsservice"
	"community.com/account/rpc/internal/svc"
	"community.com/account/rpc/pb"
)

type RelationsServiceServer struct {
	svcCtx *svc.ServiceContext
	__.UnimplementedRelationsServiceServer
}

func NewRelationsServiceServer(svcCtx *svc.ServiceContext) *RelationsServiceServer {
	return &RelationsServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *RelationsServiceServer) UserRelationsUpdate(ctx context.Context, in *__.UserRelationsUpdateReq) (*__.UserRelationsUpdateResp, error) {
	l := relationsservicelogic.NewUserRelationsUpdateLogic(ctx, s.svcCtx)
	return l.UserRelationsUpdate(in)
}

func (s *RelationsServiceServer) UserRelationsGet(ctx context.Context, in *__.UserRelationsGetReq) (*__.UserRelationsGetResp, error) {
	l := relationsservicelogic.NewUserRelationsGetLogic(ctx, s.svcCtx)
	return l.UserRelationsGet(in)
}
