// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: user.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// User 用户信息消息体
// 包含用户的完整信息，用于gRPC服务间的数据传输
type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`       // 用户唯一标识ID，主键
	Phone         string                 `protobuf:"bytes,2,opt,name=Phone,proto3" json:"Phone,omitempty"`          // 用户手机号，用于登录验证，必须唯一
	Email         string                 `protobuf:"bytes,3,opt,name=Email,proto3" json:"Email,omitempty"`          // 用户邮箱地址，可选字段
	Password      string                 `protobuf:"bytes,4,opt,name=Password,proto3" json:"Password,omitempty"`    // 用户密码，存储时应加密处理
	Nickname      string                 `protobuf:"bytes,5,opt,name=Nickname,proto3" json:"Nickname,omitempty"`    // 用户昵称，用于显示
	Avatar        string                 `protobuf:"bytes,6,opt,name=Avatar,proto3" json:"Avatar,omitempty"`        // 用户头像URL地址
	Gender        string                 `protobuf:"bytes,7,opt,name=Gender,proto3" json:"Gender,omitempty"`        // 用户性别："male"/"female"/"unknown"
	BirthDate     int64                  `protobuf:"varint,8,opt,name=BirthDate,proto3" json:"BirthDate,omitempty"` // 出生日期，Unix时间戳（毫秒）
	Role          string                 `protobuf:"bytes,9,opt,name=Role,proto3" json:"Role,omitempty"`            // 用户角色："admin"/"user"/"vip"等
	Status        int64                  `protobuf:"varint,10,opt,name=Status,proto3" json:"Status,omitempty"`      // 用户状态：0-正常 1-禁用 2-删除
	CreateAt      int64                  `protobuf:"varint,11,opt,name=createAt,proto3" json:"createAt,omitempty"`  // 账户创建时间，Unix时间戳（毫秒）
	UpdateAt      int64                  `protobuf:"varint,12,opt,name=updateAt,proto3" json:"updateAt,omitempty"`  // 最后更新时间，Unix时间戳（毫秒）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *User) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *User) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *User) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *User) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *User) GetBirthDate() int64 {
	if x != nil {
		return x.BirthDate
	}
	return 0
}

func (x *User) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *User) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *User) GetCreateAt() int64 {
	if x != nil {
		return x.CreateAt
	}
	return 0
}

func (x *User) GetUpdateAt() int64 {
	if x != nil {
		return x.UpdateAt
	}
	return 0
}

// UserLoginReq 用户登录请求消息
// 支持两种登录方式：手机号登录（推荐）或用户ID登录
type UserLoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=Phone,proto3" json:"Phone,omitempty"`       // 手机号，推荐的登录方式
	UserId        int64                  `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`    // 用户ID，备选登录方式
	Password      string                 `protobuf:"bytes,3,opt,name=Password,proto3" json:"Password,omitempty"` // 用户密码，明文传输（建议使用HTTPS）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLoginReq) Reset() {
	*x = UserLoginReq{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoginReq) ProtoMessage() {}

func (x *UserLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoginReq.ProtoReflect.Descriptor instead.
func (*UserLoginReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserLoginReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserLoginReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserLoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// UserLoginResp 用户登录响应消息
// 登录成功后返回JWT访问令牌
type UserLoginResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"` // JWT访问令牌，用于后续API调用的身份验证
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLoginResp) Reset() {
	*x = UserLoginResp{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLoginResp) ProtoMessage() {}

func (x *UserLoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLoginResp.ProtoReflect.Descriptor instead.
func (*UserLoginResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserLoginResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// UserRegisterReq 用户注册请求消息
// 新用户注册时需要提供的基本信息
type UserRegisterReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=Phone,proto3" json:"Phone,omitempty"`       // 手机号，必须唯一，作为登录凭证
	Password      string                 `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"` // 用户密码，建议8位以上包含字母数字
	Role          string                 `protobuf:"bytes,3,opt,name=Role,proto3" json:"Role,omitempty"`         // 用户角色，默认为"user"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRegisterReq) Reset() {
	*x = UserRegisterReq{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRegisterReq) ProtoMessage() {}

func (x *UserRegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRegisterReq.ProtoReflect.Descriptor instead.
func (*UserRegisterReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *UserRegisterReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserRegisterReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserRegisterReq) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

// UserRegisterResp 用户注册响应消息
// 注册成功后返回用户ID和访问令牌，实现注册即登录
type UserRegisterResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`    // JWT访问令牌，注册成功后可直接使用
	UserId        int64                  `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"` // 新创建的用户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRegisterResp) Reset() {
	*x = UserRegisterResp{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRegisterResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRegisterResp) ProtoMessage() {}

func (x *UserRegisterResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRegisterResp.ProtoReflect.Descriptor instead.
func (*UserRegisterResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *UserRegisterResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *UserRegisterResp) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// UserDeleteReq 用户删除请求消息
// 支持通过手机号或用户ID删除账户，需要密码验证确保安全
type UserDeleteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=Phone,proto3" json:"Phone,omitempty"`       // 要删除用户的手机号
	UserId        int64                  `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`    // 要删除的用户ID
	Password      string                 `protobuf:"bytes,3,opt,name=Password,proto3" json:"Password,omitempty"` // 用户密码，用于身份验证
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDeleteReq) Reset() {
	*x = UserDeleteReq{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDeleteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDeleteReq) ProtoMessage() {}

func (x *UserDeleteReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDeleteReq.ProtoReflect.Descriptor instead.
func (*UserDeleteReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *UserDeleteReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserDeleteReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserDeleteReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// UserDeleteResp 用户删除响应消息
// 返回被删除的用户信息作为操作确认
type UserDeleteResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"` // 被删除的用户完整信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDeleteResp) Reset() {
	*x = UserDeleteResp{}
	mi := &file_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDeleteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDeleteResp) ProtoMessage() {}

func (x *UserDeleteResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDeleteResp.ProtoReflect.Descriptor instead.
func (*UserDeleteResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6}
}

func (x *UserDeleteResp) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// UserUpdateReq 用户更新请求消息
// 用于更新用户信息，User对象中的UserId字段必填，其他字段按需更新
type UserUpdateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"` // 包含更新字段的用户信息，UserId必填
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserUpdateReq) Reset() {
	*x = UserUpdateReq{}
	mi := &file_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUpdateReq) ProtoMessage() {}

func (x *UserUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUpdateReq.ProtoReflect.Descriptor instead.
func (*UserUpdateReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{7}
}

func (x *UserUpdateReq) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// UserUpdateResp 用户更新响应消息
// 返回更新后的完整用户信息
type UserUpdateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"` // 更新后的用户完整信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserUpdateResp) Reset() {
	*x = UserUpdateResp{}
	mi := &file_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUpdateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUpdateResp) ProtoMessage() {}

func (x *UserUpdateResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUpdateResp.ProtoReflect.Descriptor instead.
func (*UserUpdateResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{8}
}

func (x *UserUpdateResp) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// UserQueryReq 用户查询请求消息
// 根据用户ID和查询类型获取用户信息
type UserQueryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"` // 要查询的用户ID
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`      // 查询类型："basic"-基本信息 "full"-完整信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserQueryReq) Reset() {
	*x = UserQueryReq{}
	mi := &file_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserQueryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserQueryReq) ProtoMessage() {}

func (x *UserQueryReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserQueryReq.ProtoReflect.Descriptor instead.
func (*UserQueryReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{9}
}

func (x *UserQueryReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserQueryReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// UserQueryResp 用户查询响应消息
// 根据查询类型返回对应的用户信息
type UserQueryResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"` // 用户信息，内容根据type参数决定
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserQueryResp) Reset() {
	*x = UserQueryResp{}
	mi := &file_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserQueryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserQueryResp) ProtoMessage() {}

func (x *UserQueryResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserQueryResp.ProtoReflect.Descriptor instead.
func (*UserQueryResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{10}
}

func (x *UserQueryResp) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// Relations 用户关系消息体
// 定义用户之间的各种社交关系，如好友、关注、拉黑等
type Relations struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RelationsId      int64                  `protobuf:"varint,1,opt,name=RelationsId,proto3" json:"RelationsId,omitempty"`           // 关系记录唯一标识ID
	UserId           int64                  `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`                     // 发起关系的用户ID
	OtherId          int64                  `protobuf:"varint,3,opt,name=OtherId,proto3" json:"OtherId,omitempty"`                   // 关系目标用户ID
	RelationshipType int64                  `protobuf:"varint,4,opt,name=RelationshipType,proto3" json:"RelationshipType,omitempty"` // 关系类型：1-好友 2-关注 3-拉黑 4-屏蔽
	CreateAt         int64                  `protobuf:"varint,5,opt,name=createAt,proto3" json:"createAt,omitempty"`                 // 关系建立时间，Unix时间戳（毫秒）
	UpdateAt         int64                  `protobuf:"varint,6,opt,name=updateAt,proto3" json:"updateAt,omitempty"`                 // 关系最后更新时间，Unix时间戳（毫秒）
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Relations) Reset() {
	*x = Relations{}
	mi := &file_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Relations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Relations) ProtoMessage() {}

func (x *Relations) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Relations.ProtoReflect.Descriptor instead.
func (*Relations) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{11}
}

func (x *Relations) GetRelationsId() int64 {
	if x != nil {
		return x.RelationsId
	}
	return 0
}

func (x *Relations) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Relations) GetOtherId() int64 {
	if x != nil {
		return x.OtherId
	}
	return 0
}

func (x *Relations) GetRelationshipType() int64 {
	if x != nil {
		return x.RelationshipType
	}
	return 0
}

func (x *Relations) GetCreateAt() int64 {
	if x != nil {
		return x.CreateAt
	}
	return 0
}

func (x *Relations) GetUpdateAt() int64 {
	if x != nil {
		return x.UpdateAt
	}
	return 0
}

// UserRelationsUpdateReq 用户关系更新请求消息
// 用于建立、修改或删除用户之间的关系
type UserRelationsUpdateReq struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           int64                  `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`                     // 发起操作的用户ID
	OUserId          int64                  `protobuf:"varint,2,opt,name=OUserId,proto3" json:"OUserId,omitempty"`                   // 目标用户ID
	RelationshipType int64                  `protobuf:"varint,3,opt,name=RelationshipType,proto3" json:"RelationshipType,omitempty"` // 关系类型：1-好友 2-关注 3-拉黑 4-屏蔽 0-删除关系
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UserRelationsUpdateReq) Reset() {
	*x = UserRelationsUpdateReq{}
	mi := &file_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRelationsUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRelationsUpdateReq) ProtoMessage() {}

func (x *UserRelationsUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRelationsUpdateReq.ProtoReflect.Descriptor instead.
func (*UserRelationsUpdateReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{12}
}

func (x *UserRelationsUpdateReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserRelationsUpdateReq) GetOUserId() int64 {
	if x != nil {
		return x.OUserId
	}
	return 0
}

func (x *UserRelationsUpdateReq) GetRelationshipType() int64 {
	if x != nil {
		return x.RelationshipType
	}
	return 0
}

// UserRelationsUpdateResp 用户关系更新响应消息
// 返回更新后的关系详细信息
type UserRelationsUpdateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Relations     *Relations             `protobuf:"bytes,1,opt,name=Relations,proto3" json:"Relations,omitempty"` // 更新后的关系详细信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRelationsUpdateResp) Reset() {
	*x = UserRelationsUpdateResp{}
	mi := &file_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRelationsUpdateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRelationsUpdateResp) ProtoMessage() {}

func (x *UserRelationsUpdateResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRelationsUpdateResp.ProtoReflect.Descriptor instead.
func (*UserRelationsUpdateResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{13}
}

func (x *UserRelationsUpdateResp) GetRelations() *Relations {
	if x != nil {
		return x.Relations
	}
	return nil
}

// UserRelationsGetReq 用户关系查询请求消息
// 查询两个用户之间的关系状态
type UserRelationsGetReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`   // 查询发起用户ID
	OUserId       int64                  `protobuf:"varint,2,opt,name=OUserId,proto3" json:"OUserId,omitempty"` // 查询目标用户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRelationsGetReq) Reset() {
	*x = UserRelationsGetReq{}
	mi := &file_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRelationsGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRelationsGetReq) ProtoMessage() {}

func (x *UserRelationsGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRelationsGetReq.ProtoReflect.Descriptor instead.
func (*UserRelationsGetReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{14}
}

func (x *UserRelationsGetReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserRelationsGetReq) GetOUserId() int64 {
	if x != nil {
		return x.OUserId
	}
	return 0
}

// UserRelationsGetResp 用户关系查询响应消息
// 返回两个用户之间的关系详情
type UserRelationsGetResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Relations     *Relations             `protobuf:"bytes,1,opt,name=Relations,proto3" json:"Relations,omitempty"` // 用户关系详细信息，如果无关系则为空
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRelationsGetResp) Reset() {
	*x = UserRelationsGetResp{}
	mi := &file_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRelationsGetResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRelationsGetResp) ProtoMessage() {}

func (x *UserRelationsGetResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRelationsGetResp.ProtoReflect.Descriptor instead.
func (*UserRelationsGetResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{15}
}

func (x *UserRelationsGetResp) GetRelations() *Relations {
	if x != nil {
		return x.Relations
	}
	return nil
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x04user\"\xb4\x02\n" +
	"\x04User\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x03R\x06UserId\x12\x14\n" +
	"\x05Phone\x18\x02 \x01(\tR\x05Phone\x12\x14\n" +
	"\x05Email\x18\x03 \x01(\tR\x05Email\x12\x1a\n" +
	"\bPassword\x18\x04 \x01(\tR\bPassword\x12\x1a\n" +
	"\bNickname\x18\x05 \x01(\tR\bNickname\x12\x16\n" +
	"\x06Avatar\x18\x06 \x01(\tR\x06Avatar\x12\x16\n" +
	"\x06Gender\x18\a \x01(\tR\x06Gender\x12\x1c\n" +
	"\tBirthDate\x18\b \x01(\x03R\tBirthDate\x12\x12\n" +
	"\x04Role\x18\t \x01(\tR\x04Role\x12\x16\n" +
	"\x06Status\x18\n" +
	" \x01(\x03R\x06Status\x12\x1a\n" +
	"\bcreateAt\x18\v \x01(\x03R\bcreateAt\x12\x1a\n" +
	"\bupdateAt\x18\f \x01(\x03R\bupdateAt\"X\n" +
	"\fUserLoginReq\x12\x14\n" +
	"\x05Phone\x18\x01 \x01(\tR\x05Phone\x12\x16\n" +
	"\x06UserId\x18\x02 \x01(\x03R\x06UserId\x12\x1a\n" +
	"\bPassword\x18\x03 \x01(\tR\bPassword\"%\n" +
	"\rUserLoginResp\x12\x14\n" +
	"\x05Token\x18\x01 \x01(\tR\x05Token\"W\n" +
	"\x0fUserRegisterReq\x12\x14\n" +
	"\x05Phone\x18\x01 \x01(\tR\x05Phone\x12\x1a\n" +
	"\bPassword\x18\x02 \x01(\tR\bPassword\x12\x12\n" +
	"\x04Role\x18\x03 \x01(\tR\x04Role\"@\n" +
	"\x10UserRegisterResp\x12\x14\n" +
	"\x05Token\x18\x01 \x01(\tR\x05Token\x12\x16\n" +
	"\x06UserId\x18\x02 \x01(\x03R\x06UserId\"Y\n" +
	"\rUserDeleteReq\x12\x14\n" +
	"\x05Phone\x18\x01 \x01(\tR\x05Phone\x12\x16\n" +
	"\x06UserId\x18\x02 \x01(\x03R\x06UserId\x12\x1a\n" +
	"\bPassword\x18\x03 \x01(\tR\bPassword\"0\n" +
	"\x0eUserDeleteResp\x12\x1e\n" +
	"\x04User\x18\x01 \x01(\v2\n" +
	".user.UserR\x04User\"/\n" +
	"\rUserUpdateReq\x12\x1e\n" +
	"\x04User\x18\x01 \x01(\v2\n" +
	".user.UserR\x04User\"0\n" +
	"\x0eUserUpdateResp\x12\x1e\n" +
	"\x04User\x18\x01 \x01(\v2\n" +
	".user.UserR\x04User\":\n" +
	"\fUserQueryReq\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x03R\x06UserId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"/\n" +
	"\rUserQueryResp\x12\x1e\n" +
	"\x04User\x18\x01 \x01(\v2\n" +
	".user.UserR\x04User\"\xc3\x01\n" +
	"\tRelations\x12 \n" +
	"\vRelationsId\x18\x01 \x01(\x03R\vRelationsId\x12\x16\n" +
	"\x06UserId\x18\x02 \x01(\x03R\x06UserId\x12\x18\n" +
	"\aOtherId\x18\x03 \x01(\x03R\aOtherId\x12*\n" +
	"\x10RelationshipType\x18\x04 \x01(\x03R\x10RelationshipType\x12\x1a\n" +
	"\bcreateAt\x18\x05 \x01(\x03R\bcreateAt\x12\x1a\n" +
	"\bupdateAt\x18\x06 \x01(\x03R\bupdateAt\"v\n" +
	"\x16UserRelationsUpdateReq\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x03R\x06UserId\x12\x18\n" +
	"\aOUserId\x18\x02 \x01(\x03R\aOUserId\x12*\n" +
	"\x10RelationshipType\x18\x03 \x01(\x03R\x10RelationshipType\"H\n" +
	"\x17UserRelationsUpdateResp\x12-\n" +
	"\tRelations\x18\x01 \x01(\v2\x0f.user.RelationsR\tRelations\"G\n" +
	"\x13UserRelationsGetReq\x12\x16\n" +
	"\x06UserId\x18\x01 \x01(\x03R\x06UserId\x12\x18\n" +
	"\aOUserId\x18\x02 \x01(\x03R\aOUserId\"E\n" +
	"\x14UserRelationsGetResp\x12-\n" +
	"\tRelations\x18\x01 \x01(\v2\x0f.user.RelationsR\tRelations2\xaa\x02\n" +
	"\vUserService\x124\n" +
	"\tUserLogin\x12\x12.user.UserLoginReq\x1a\x13.user.UserLoginResp\x12=\n" +
	"\fUserRegister\x12\x15.user.UserRegisterReq\x1a\x16.user.UserRegisterResp\x127\n" +
	"\n" +
	"UserDelete\x12\x13.user.UserDeleteReq\x1a\x14.user.UserDeleteResp\x127\n" +
	"\n" +
	"UserUpdate\x12\x13.user.UserUpdateReq\x1a\x14.user.UserUpdateResp\x124\n" +
	"\tUserQuery\x12\x12.user.UserQueryReq\x1a\x13.user.UserQueryResp2\xb1\x01\n" +
	"\x10RelationsService\x12R\n" +
	"\x13UserRelationsUpdate\x12\x1c.user.UserRelationsUpdateReq\x1a\x1d.user.UserRelationsUpdateResp\x12I\n" +
	"\x10UserRelationsGet\x12\x19.user.UserRelationsGetReq\x1a\x1a.user.UserRelationsGetRespB\x04Z\x02./b\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_user_proto_goTypes = []any{
	(*User)(nil),                    // 0: user.User
	(*UserLoginReq)(nil),            // 1: user.UserLoginReq
	(*UserLoginResp)(nil),           // 2: user.UserLoginResp
	(*UserRegisterReq)(nil),         // 3: user.UserRegisterReq
	(*UserRegisterResp)(nil),        // 4: user.UserRegisterResp
	(*UserDeleteReq)(nil),           // 5: user.UserDeleteReq
	(*UserDeleteResp)(nil),          // 6: user.UserDeleteResp
	(*UserUpdateReq)(nil),           // 7: user.UserUpdateReq
	(*UserUpdateResp)(nil),          // 8: user.UserUpdateResp
	(*UserQueryReq)(nil),            // 9: user.UserQueryReq
	(*UserQueryResp)(nil),           // 10: user.UserQueryResp
	(*Relations)(nil),               // 11: user.Relations
	(*UserRelationsUpdateReq)(nil),  // 12: user.UserRelationsUpdateReq
	(*UserRelationsUpdateResp)(nil), // 13: user.UserRelationsUpdateResp
	(*UserRelationsGetReq)(nil),     // 14: user.UserRelationsGetReq
	(*UserRelationsGetResp)(nil),    // 15: user.UserRelationsGetResp
}
var file_user_proto_depIdxs = []int32{
	0,  // 0: user.UserDeleteResp.User:type_name -> user.User
	0,  // 1: user.UserUpdateReq.User:type_name -> user.User
	0,  // 2: user.UserUpdateResp.User:type_name -> user.User
	0,  // 3: user.UserQueryResp.User:type_name -> user.User
	11, // 4: user.UserRelationsUpdateResp.Relations:type_name -> user.Relations
	11, // 5: user.UserRelationsGetResp.Relations:type_name -> user.Relations
	1,  // 6: user.UserService.UserLogin:input_type -> user.UserLoginReq
	3,  // 7: user.UserService.UserRegister:input_type -> user.UserRegisterReq
	5,  // 8: user.UserService.UserDelete:input_type -> user.UserDeleteReq
	7,  // 9: user.UserService.UserUpdate:input_type -> user.UserUpdateReq
	9,  // 10: user.UserService.UserQuery:input_type -> user.UserQueryReq
	12, // 11: user.RelationsService.UserRelationsUpdate:input_type -> user.UserRelationsUpdateReq
	14, // 12: user.RelationsService.UserRelationsGet:input_type -> user.UserRelationsGetReq
	2,  // 13: user.UserService.UserLogin:output_type -> user.UserLoginResp
	4,  // 14: user.UserService.UserRegister:output_type -> user.UserRegisterResp
	6,  // 15: user.UserService.UserDelete:output_type -> user.UserDeleteResp
	8,  // 16: user.UserService.UserUpdate:output_type -> user.UserUpdateResp
	10, // 17: user.UserService.UserQuery:output_type -> user.UserQueryResp
	13, // 18: user.RelationsService.UserRelationsUpdate:output_type -> user.UserRelationsUpdateResp
	15, // 19: user.RelationsService.UserRelationsGet:output_type -> user.UserRelationsGetResp
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
