// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: user.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	UserService_UserLogin_FullMethodName    = "/user.UserService/UserLogin"
	UserService_UserRegister_FullMethodName = "/user.UserService/UserRegister"
	UserService_UserDelete_FullMethodName   = "/user.UserService/UserDelete"
	UserService_UserUpdate_FullMethodName   = "/user.UserService/UserUpdate"
	UserService_UserQuery_FullMethodName    = "/user.UserService/UserQuery"
)

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserServiceClient interface {
	// UserLogin 用户登录
	// 验证用户凭证并返回JWT访问令牌
	UserLogin(ctx context.Context, in *UserLoginReq, opts ...grpc.CallOption) (*UserLoginResp, error)
	// UserRegister 用户注册
	// 创建新用户账户，注册成功后自动登录
	UserRegister(ctx context.Context, in *UserRegisterReq, opts ...grpc.CallOption) (*UserRegisterResp, error)
	// UserDelete 用户删除
	// 删除用户账户，通常执行软删除以保留数据完整性
	UserDelete(ctx context.Context, in *UserDeleteReq, opts ...grpc.CallOption) (*UserDeleteResp, error)
	// UserUpdate 用户信息更新
	// 更新用户的基本信息，如昵称、头像、个人资料等
	UserUpdate(ctx context.Context, in *UserUpdateReq, opts ...grpc.CallOption) (*UserUpdateResp, error)
	// UserQuery 用户信息查询
	// 根据用户ID和查询类型获取用户信息
	UserQuery(ctx context.Context, in *UserQueryReq, opts ...grpc.CallOption) (*UserQueryResp, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) UserLogin(ctx context.Context, in *UserLoginReq, opts ...grpc.CallOption) (*UserLoginResp, error) {
	out := new(UserLoginResp)
	err := c.cc.Invoke(ctx, UserService_UserLogin_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UserRegister(ctx context.Context, in *UserRegisterReq, opts ...grpc.CallOption) (*UserRegisterResp, error) {
	out := new(UserRegisterResp)
	err := c.cc.Invoke(ctx, UserService_UserRegister_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UserDelete(ctx context.Context, in *UserDeleteReq, opts ...grpc.CallOption) (*UserDeleteResp, error) {
	out := new(UserDeleteResp)
	err := c.cc.Invoke(ctx, UserService_UserDelete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UserUpdate(ctx context.Context, in *UserUpdateReq, opts ...grpc.CallOption) (*UserUpdateResp, error) {
	out := new(UserUpdateResp)
	err := c.cc.Invoke(ctx, UserService_UserUpdate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UserQuery(ctx context.Context, in *UserQueryReq, opts ...grpc.CallOption) (*UserQueryResp, error) {
	out := new(UserQueryResp)
	err := c.cc.Invoke(ctx, UserService_UserQuery_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility
type UserServiceServer interface {
	// UserLogin 用户登录
	// 验证用户凭证并返回JWT访问令牌
	UserLogin(context.Context, *UserLoginReq) (*UserLoginResp, error)
	// UserRegister 用户注册
	// 创建新用户账户，注册成功后自动登录
	UserRegister(context.Context, *UserRegisterReq) (*UserRegisterResp, error)
	// UserDelete 用户删除
	// 删除用户账户，通常执行软删除以保留数据完整性
	UserDelete(context.Context, *UserDeleteReq) (*UserDeleteResp, error)
	// UserUpdate 用户信息更新
	// 更新用户的基本信息，如昵称、头像、个人资料等
	UserUpdate(context.Context, *UserUpdateReq) (*UserUpdateResp, error)
	// UserQuery 用户信息查询
	// 根据用户ID和查询类型获取用户信息
	UserQuery(context.Context, *UserQueryReq) (*UserQueryResp, error)
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (UnimplementedUserServiceServer) UserLogin(context.Context, *UserLoginReq) (*UserLoginResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserLogin not implemented")
}
func (UnimplementedUserServiceServer) UserRegister(context.Context, *UserRegisterReq) (*UserRegisterResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserRegister not implemented")
}
func (UnimplementedUserServiceServer) UserDelete(context.Context, *UserDeleteReq) (*UserDeleteResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserDelete not implemented")
}
func (UnimplementedUserServiceServer) UserUpdate(context.Context, *UserUpdateReq) (*UserUpdateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserUpdate not implemented")
}
func (UnimplementedUserServiceServer) UserQuery(context.Context, *UserQueryReq) (*UserQueryResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserQuery not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_UserLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserLoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UserLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UserLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UserLogin(ctx, req.(*UserLoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UserRegister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRegisterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UserRegister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UserRegister_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UserRegister(ctx, req.(*UserRegisterReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UserDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UserDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UserDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UserDelete(ctx, req.(*UserDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UserUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UserUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UserUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UserUpdate(ctx, req.(*UserUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UserQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserQueryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UserQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UserQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UserQuery(ctx, req.(*UserQueryReq))
	}
	return interceptor(ctx, in, info, handler)
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UserLogin",
			Handler:    _UserService_UserLogin_Handler,
		},
		{
			MethodName: "UserRegister",
			Handler:    _UserService_UserRegister_Handler,
		},
		{
			MethodName: "UserDelete",
			Handler:    _UserService_UserDelete_Handler,
		},
		{
			MethodName: "UserUpdate",
			Handler:    _UserService_UserUpdate_Handler,
		},
		{
			MethodName: "UserQuery",
			Handler:    _UserService_UserQuery_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}

const (
	RelationsService_UserRelationsUpdate_FullMethodName = "/user.RelationsService/UserRelationsUpdate"
	RelationsService_UserRelationsGet_FullMethodName    = "/user.RelationsService/UserRelationsGet"
)

// RelationsServiceClient is the client API for RelationsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RelationsServiceClient interface {
	// UserRelationsUpdate 用户关系更新
	// 建立、修改或删除用户之间的关系
	UserRelationsUpdate(ctx context.Context, in *UserRelationsUpdateReq, opts ...grpc.CallOption) (*UserRelationsUpdateResp, error)
	// UserRelationsGet 用户关系查询
	// 查询两个用户之间的关系状态和详细信息
	UserRelationsGet(ctx context.Context, in *UserRelationsGetReq, opts ...grpc.CallOption) (*UserRelationsGetResp, error)
}

type relationsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRelationsServiceClient(cc grpc.ClientConnInterface) RelationsServiceClient {
	return &relationsServiceClient{cc}
}

func (c *relationsServiceClient) UserRelationsUpdate(ctx context.Context, in *UserRelationsUpdateReq, opts ...grpc.CallOption) (*UserRelationsUpdateResp, error) {
	out := new(UserRelationsUpdateResp)
	err := c.cc.Invoke(ctx, RelationsService_UserRelationsUpdate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relationsServiceClient) UserRelationsGet(ctx context.Context, in *UserRelationsGetReq, opts ...grpc.CallOption) (*UserRelationsGetResp, error) {
	out := new(UserRelationsGetResp)
	err := c.cc.Invoke(ctx, RelationsService_UserRelationsGet_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RelationsServiceServer is the server API for RelationsService service.
// All implementations must embed UnimplementedRelationsServiceServer
// for forward compatibility
type RelationsServiceServer interface {
	// UserRelationsUpdate 用户关系更新
	// 建立、修改或删除用户之间的关系
	UserRelationsUpdate(context.Context, *UserRelationsUpdateReq) (*UserRelationsUpdateResp, error)
	// UserRelationsGet 用户关系查询
	// 查询两个用户之间的关系状态和详细信息
	UserRelationsGet(context.Context, *UserRelationsGetReq) (*UserRelationsGetResp, error)
	mustEmbedUnimplementedRelationsServiceServer()
}

// UnimplementedRelationsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRelationsServiceServer struct {
}

func (UnimplementedRelationsServiceServer) UserRelationsUpdate(context.Context, *UserRelationsUpdateReq) (*UserRelationsUpdateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserRelationsUpdate not implemented")
}
func (UnimplementedRelationsServiceServer) UserRelationsGet(context.Context, *UserRelationsGetReq) (*UserRelationsGetResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserRelationsGet not implemented")
}
func (UnimplementedRelationsServiceServer) mustEmbedUnimplementedRelationsServiceServer() {}

// UnsafeRelationsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RelationsServiceServer will
// result in compilation errors.
type UnsafeRelationsServiceServer interface {
	mustEmbedUnimplementedRelationsServiceServer()
}

func RegisterRelationsServiceServer(s grpc.ServiceRegistrar, srv RelationsServiceServer) {
	s.RegisterService(&RelationsService_ServiceDesc, srv)
}

func _RelationsService_UserRelationsUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRelationsUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelationsServiceServer).UserRelationsUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelationsService_UserRelationsUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelationsServiceServer).UserRelationsUpdate(ctx, req.(*UserRelationsUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelationsService_UserRelationsGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRelationsGetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelationsServiceServer).UserRelationsGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelationsService_UserRelationsGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelationsServiceServer).UserRelationsGet(ctx, req.(*UserRelationsGetReq))
	}
	return interceptor(ctx, in, info, handler)
}

// RelationsService_ServiceDesc is the grpc.ServiceDesc for RelationsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RelationsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.RelationsService",
	HandlerType: (*RelationsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UserRelationsUpdate",
			Handler:    _RelationsService_UserRelationsUpdate_Handler,
		},
		{
			MethodName: "UserRelationsGet",
			Handler:    _RelationsService_UserRelationsGet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
