// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: message.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`                                   // 文本内容
	MessageType   int64                  `protobuf:"varint,2,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"` // 消息类型
	Addition      string                 `protobuf:"bytes,3,opt,name=addition,proto3" json:"addition,omitempty"`                           // 附加消息（图片/文件等，JSON格式）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageContent) Reset() {
	*x = MessageContent{}
	mi := &file_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageContent) ProtoMessage() {}

func (x *MessageContent) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageContent.ProtoReflect.Descriptor instead.
func (*MessageContent) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (x *MessageContent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *MessageContent) GetMessageType() int64 {
	if x != nil {
		return x.MessageType
	}
	return 0
}

func (x *MessageContent) GetAddition() string {
	if x != nil {
		return x.Addition
	}
	return ""
}

type MessageDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`    // 消息唯一ID
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`     // 会话ID（关联群聊或单聊）
	SendId        int64                  `protobuf:"varint,3,opt,name=send_id,json=sendId,proto3" json:"send_id,omitempty"`             // 发送者ID
	ReplyId       int64                  `protobuf:"varint,4,opt,name=reply_id,json=replyId,proto3" json:"reply_id,omitempty"`          // 回复的消息ID（0表示非回复）
	CreateTime    int64                  `protobuf:"varint,5,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"` // 创建时间（毫秒级时间戳）
	UpdateTime    int64                  `protobuf:"varint,6,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"` // 更新时间（编辑/撤回时更新）
	Status        int64                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`                           // 消息状态
	Content       *MessageContent        `protobuf:"bytes,8,opt,name=content,proto3" json:"content,omitempty"`                          // 消息内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageDetail) Reset() {
	*x = MessageDetail{}
	mi := &file_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageDetail) ProtoMessage() {}

func (x *MessageDetail) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageDetail.ProtoReflect.Descriptor instead.
func (*MessageDetail) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

func (x *MessageDetail) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *MessageDetail) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *MessageDetail) GetSendId() int64 {
	if x != nil {
		return x.SendId
	}
	return 0
}

func (x *MessageDetail) GetReplyId() int64 {
	if x != nil {
		return x.ReplyId
	}
	return 0
}

func (x *MessageDetail) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *MessageDetail) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *MessageDetail) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *MessageDetail) GetContent() *MessageContent {
	if x != nil {
		return x.Content
	}
	return nil
}

type GetMessageByIdsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	MessageId     []int64                `protobuf:"varint,2,rep,packed,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageByIdsReq) Reset() {
	*x = GetMessageByIdsReq{}
	mi := &file_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageByIdsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageByIdsReq) ProtoMessage() {}

func (x *GetMessageByIdsReq) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageByIdsReq.ProtoReflect.Descriptor instead.
func (*GetMessageByIdsReq) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{2}
}

func (x *GetMessageByIdsReq) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetMessageByIdsReq) GetMessageId() []int64 {
	if x != nil {
		return x.MessageId
	}
	return nil
}

type GetMessageByIdsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       []*MessageDetail       `protobuf:"bytes,1,rep,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageByIdsResp) Reset() {
	*x = GetMessageByIdsResp{}
	mi := &file_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageByIdsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageByIdsResp) ProtoMessage() {}

func (x *GetMessageByIdsResp) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageByIdsResp.ProtoReflect.Descriptor instead.
func (*GetMessageByIdsResp) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{3}
}

func (x *GetMessageByIdsResp) GetMessage() []*MessageDetail {
	if x != nil {
		return x.Message
	}
	return nil
}

type GetMessageListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Req           int64                  `protobuf:"varint,2,opt,name=req,proto3" json:"req,omitempty"`
	Limit         int64                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageListReq) Reset() {
	*x = GetMessageListReq{}
	mi := &file_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageListReq) ProtoMessage() {}

func (x *GetMessageListReq) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageListReq.ProtoReflect.Descriptor instead.
func (*GetMessageListReq) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{4}
}

func (x *GetMessageListReq) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetMessageListReq) GetReq() int64 {
	if x != nil {
		return x.Req
	}
	return 0
}

func (x *GetMessageListReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetMessageListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       []*MessageDetail       `protobuf:"bytes,1,rep,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageListResp) Reset() {
	*x = GetMessageListResp{}
	mi := &file_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageListResp) ProtoMessage() {}

func (x *GetMessageListResp) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageListResp.ProtoReflect.Descriptor instead.
func (*GetMessageListResp) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{5}
}

func (x *GetMessageListResp) GetMessage() []*MessageDetail {
	if x != nil {
		return x.Message
	}
	return nil
}

type CreateMessageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *MessageDetail         `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMessageReq) Reset() {
	*x = CreateMessageReq{}
	mi := &file_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMessageReq) ProtoMessage() {}

func (x *CreateMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMessageReq.ProtoReflect.Descriptor instead.
func (*CreateMessageReq) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{6}
}

func (x *CreateMessageReq) GetMessage() *MessageDetail {
	if x != nil {
		return x.Message
	}
	return nil
}

type CreateMessageResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMessageResp) Reset() {
	*x = CreateMessageResp{}
	mi := &file_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMessageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMessageResp) ProtoMessage() {}

func (x *CreateMessageResp) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMessageResp.ProtoReflect.Descriptor instead.
func (*CreateMessageResp) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{7}
}

type UpdateMessageByIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *MessageDetail         `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMessageByIdReq) Reset() {
	*x = UpdateMessageByIdReq{}
	mi := &file_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMessageByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMessageByIdReq) ProtoMessage() {}

func (x *UpdateMessageByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMessageByIdReq.ProtoReflect.Descriptor instead.
func (*UpdateMessageByIdReq) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateMessageByIdReq) GetMessage() *MessageDetail {
	if x != nil {
		return x.Message
	}
	return nil
}

type UpdateMessageByIdResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMessageByIdResp) Reset() {
	*x = UpdateMessageByIdResp{}
	mi := &file_message_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMessageByIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMessageByIdResp) ProtoMessage() {}

func (x *UpdateMessageByIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMessageByIdResp.ProtoReflect.Descriptor instead.
func (*UpdateMessageByIdResp) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{9}
}

type DeleteMessageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // 删除的会话id
	SendId        int64                  `protobuf:"varint,2,opt,name=send_id,json=sendId,proto3" json:"send_id,omitempty"`         // 删除的发送者id
	MessageId     int64                  `protobuf:"varint,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessageReq) Reset() {
	*x = DeleteMessageReq{}
	mi := &file_message_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessageReq) ProtoMessage() {}

func (x *DeleteMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessageReq.ProtoReflect.Descriptor instead.
func (*DeleteMessageReq) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteMessageReq) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *DeleteMessageReq) GetSendId() int64 {
	if x != nil {
		return x.SendId
	}
	return 0
}

func (x *DeleteMessageReq) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

type DeleteMessageResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessageResp) Reset() {
	*x = DeleteMessageResp{}
	mi := &file_message_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessageResp) ProtoMessage() {}

func (x *DeleteMessageResp) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessageResp.ProtoReflect.Descriptor instead.
func (*DeleteMessageResp) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{11}
}

var File_message_proto protoreflect.FileDescriptor

const file_message_proto_rawDesc = "" +
	"\n" +
	"\rmessage.proto\x12\amessage\"c\n" +
	"\x0eMessageContent\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12!\n" +
	"\fmessage_type\x18\x02 \x01(\x03R\vmessageType\x12\x1a\n" +
	"\baddition\x18\x03 \x01(\tR\baddition\"\x8e\x02\n" +
	"\rMessageDetail\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x17\n" +
	"\asend_id\x18\x03 \x01(\x03R\x06sendId\x12\x19\n" +
	"\breply_id\x18\x04 \x01(\x03R\areplyId\x12\x1f\n" +
	"\vcreate_time\x18\x05 \x01(\x03R\n" +
	"createTime\x12\x1f\n" +
	"\vupdate_time\x18\x06 \x01(\x03R\n" +
	"updateTime\x12\x16\n" +
	"\x06status\x18\a \x01(\x03R\x06status\x121\n" +
	"\acontent\x18\b \x01(\v2\x17.message.MessageContentR\acontent\"R\n" +
	"\x12GetMessageByIdsReq\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x03(\x03R\tmessageId\"G\n" +
	"\x13GetMessageByIdsResp\x120\n" +
	"\amessage\x18\x01 \x03(\v2\x16.message.MessageDetailR\amessage\"Z\n" +
	"\x11GetMessageListReq\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x10\n" +
	"\x03req\x18\x02 \x01(\x03R\x03req\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x03R\x05limit\"F\n" +
	"\x12GetMessageListResp\x120\n" +
	"\amessage\x18\x01 \x03(\v2\x16.message.MessageDetailR\amessage\"D\n" +
	"\x10CreateMessageReq\x120\n" +
	"\amessage\x18\x01 \x01(\v2\x16.message.MessageDetailR\amessage\"\x13\n" +
	"\x11CreateMessageResp\"H\n" +
	"\x14UpdateMessageByIdReq\x120\n" +
	"\amessage\x18\x01 \x01(\v2\x16.message.MessageDetailR\amessage\"\x17\n" +
	"\x15UpdateMessageByIdResp\"i\n" +
	"\x10DeleteMessageReq\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\asend_id\x18\x02 \x01(\x03R\x06sendId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\x03R\tmessageId\"\x13\n" +
	"\x11DeleteMessageResp2\x86\x03\n" +
	"\aMessage\x12L\n" +
	"\x0fGetMessageByIds\x12\x1b.message.GetMessageByIdsReq\x1a\x1c.message.GetMessageByIdsResp\x12I\n" +
	"\x0eGetMessageList\x12\x1a.message.GetMessageListReq\x1a\x1b.message.GetMessageListResp\x12F\n" +
	"\rCreateMessage\x12\x19.message.CreateMessageReq\x1a\x1a.message.CreateMessageResp\x12R\n" +
	"\x11UpdateMessageById\x12\x1d.message.UpdateMessageByIdReq\x1a\x1e.message.UpdateMessageByIdResp\x12F\n" +
	"\rDeleteMessage\x12\x19.message.DeleteMessageReq\x1a\x1a.message.DeleteMessageRespB\x04Z\x02./b\x06proto3"

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData []byte
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)))
	})
	return file_message_proto_rawDescData
}

var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_message_proto_goTypes = []any{
	(*MessageContent)(nil),        // 0: message.MessageContent
	(*MessageDetail)(nil),         // 1: message.MessageDetail
	(*GetMessageByIdsReq)(nil),    // 2: message.GetMessageByIdsReq
	(*GetMessageByIdsResp)(nil),   // 3: message.GetMessageByIdsResp
	(*GetMessageListReq)(nil),     // 4: message.GetMessageListReq
	(*GetMessageListResp)(nil),    // 5: message.GetMessageListResp
	(*CreateMessageReq)(nil),      // 6: message.CreateMessageReq
	(*CreateMessageResp)(nil),     // 7: message.CreateMessageResp
	(*UpdateMessageByIdReq)(nil),  // 8: message.UpdateMessageByIdReq
	(*UpdateMessageByIdResp)(nil), // 9: message.UpdateMessageByIdResp
	(*DeleteMessageReq)(nil),      // 10: message.DeleteMessageReq
	(*DeleteMessageResp)(nil),     // 11: message.DeleteMessageResp
}
var file_message_proto_depIdxs = []int32{
	0,  // 0: message.MessageDetail.content:type_name -> message.MessageContent
	1,  // 1: message.GetMessageByIdsResp.message:type_name -> message.MessageDetail
	1,  // 2: message.GetMessageListResp.message:type_name -> message.MessageDetail
	1,  // 3: message.CreateMessageReq.message:type_name -> message.MessageDetail
	1,  // 4: message.UpdateMessageByIdReq.message:type_name -> message.MessageDetail
	2,  // 5: message.Message.GetMessageByIds:input_type -> message.GetMessageByIdsReq
	4,  // 6: message.Message.GetMessageList:input_type -> message.GetMessageListReq
	6,  // 7: message.Message.CreateMessage:input_type -> message.CreateMessageReq
	8,  // 8: message.Message.UpdateMessageById:input_type -> message.UpdateMessageByIdReq
	10, // 9: message.Message.DeleteMessage:input_type -> message.DeleteMessageReq
	3,  // 10: message.Message.GetMessageByIds:output_type -> message.GetMessageByIdsResp
	5,  // 11: message.Message.GetMessageList:output_type -> message.GetMessageListResp
	7,  // 12: message.Message.CreateMessage:output_type -> message.CreateMessageResp
	9,  // 13: message.Message.UpdateMessageById:output_type -> message.UpdateMessageByIdResp
	11, // 14: message.Message.DeleteMessage:output_type -> message.DeleteMessageResp
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
