// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3
// Source: weather.proto

package server

import (
	"context"

	"community.com/service/weather/rpc/internal/logic/weatherservice"
	"community.com/service/weather/rpc/internal/svc"
	"community.com/service/weather/rpc/pb"
)

type WeatherServiceServer struct {
	svcCtx *svc.ServiceContext
	__.UnimplementedWeatherServiceServer
}

func NewWeatherServiceServer(svcCtx *svc.ServiceContext) *WeatherServiceServer {
	return &WeatherServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *WeatherServiceServer) WeatherAddData(ctx context.Context, in *__.WeatherAddDataReq) (*__.WeatherAddDataResp, error) {
	l := weatherservicelogic.NewWeatherAddDataLogic(ctx, s.svcCtx)
	return l.WeatherAddData(in)
}
