// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: websocketpush.proto

package websocketpush

import (
	"context"

	"community/service/websocketpush/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	WebSocketPushData = __.WebSocketPushData
	WebSocketPushReq  = __.WebSocketPushReq
	WebSocketPushResp = __.WebSocketPushResp

	WebsocketPush interface {
		WebSocketPush(ctx context.Context, in *WebSocketPushReq, opts ...grpc.CallOption) (*WebSocketPushResp, error)
	}

	defaultWebsocketPush struct {
		cli zrpc.Client
	}
)

func NewWebsocketPush(cli zrpc.Client) WebsocketPush {
	return &defaultWebsocketPush{
		cli: cli,
	}
}

func (m *defaultWebsocketPush) WebSocketPush(ctx context.Context, in *WebSocketPushReq, opts ...grpc.CallOption) (*WebSocketPushResp, error) {
	client := __.NewWebsocketPushClient(m.cli.Conn())
	return client.WebSocketPush(ctx, in, opts...)
}
