// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type PostCreateReq struct {
	Title   string `json:"title"`   // 标题
	Content string `json:"content"` // 内容
	Images  string `json:"images"`  // 图片列表
	Theme   string `json:"theme"`   // 主题
	Tags    string `json:"tags"`    // 标签
	Status  int32  `json:"status"`  // 状态
}

type PostCreateResp struct {
	PostId int64 `json:"post_id"` // 帖子ID
}

type PostDeleteReq struct {
	PostId int64 `json:"post_id"` // 帖子ID
}

type PostDeleteResp struct {
}

type PostUpdateReq struct {
	PostId  int64  `json:"post_id"` // 帖子ID
	Title   string `json:"title"`   // 标题
	Content string `json:"content"` // 内容
	Images  string `json:"images"`  // 图片列表
	Theme   string `json:"theme"`   // 主题
	Tags    string `json:"tags"`    // 标签
	Status  int32  `json:"status"`  // 状态
}

type PostUpdateResp struct {
}
