// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type PostDetailReq struct {
	PostId int64 `json:"post_id"` // 帖子ID
}

type PostDetailResp struct {
	Post PostDetail `json:"post"` // 帖子信息
}

type PostListReq struct {
	Page     int64  `json:"page"`      // 页码
	PageSize int64  `json:"page_size"` // 每页数量
	Theme    string `json:"theme"`     // 主题筛选
	UserId   int64  `json:"user_id"`   // 用户ID筛选
	Keyword  string `json:"keyword"`   // 关键词搜索
	SortBy   string `json:"sort_by"`   // 排序方式
}

type PostListResp struct {
	Posts    []PostDetail `json:"posts"`     // 帖子列表
	Total    int64        `json:"total"`     // 总数量
	Page     int64        `json:"page"`      // 当前页码
	PageSize int64        `json:"page_size"` // 每页数量
}
