// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0

package types

type PostAuthor struct {
	UserId   int64  `json:"user_id"`   // 用户ID
	NickName string `json:"nick_name"` // 昵称
	Avatar   string `json:"avatar"`    // 头像
}

type PostBase struct {
	PostId     int64  `json:"post_id"`     // 帖子ID
	UserId     int64  `json:"user_id"`     // 发布者ID
	Title      string `json:"title"`       // 标题
	Content    string `json:"content"`     // 内容
	Images     string `json:"images"`      // 图片列表
	Theme      string `json:"theme"`       // 主题
	Tags       string `json:"tags"`        // 标签
	Status     int32  `json:"status"`      // 状态
	CreateTime int64  `json:"create_time"` // 创建时间
	UpdateTime int64  `json:"update_time"` // 更新时间
}

type PostCreateReq struct {
	Title   string `json:"title"`   // 标题
	Content string `json:"content"` // 内容
	Images  string `json:"images"`  // 图片列表
	Theme   string `json:"theme"`   // 主题
	Tags    string `json:"tags"`    // 标签
	Status  int32  `json:"status"`  // 状态
}

type PostCreateResp struct {
	PostId int64 `json:"post_id"` // 帖子ID
}

type PostDeleteReq struct {
	PostId int64 `json:"post_id"` // 帖子ID
}

type PostDeleteResp struct {
}

type PostDetail struct {
	PostBase    PostBase   `json:"post_base"`    // 基本信息
	PostStats   PostStats  `json:"post_stats"`   // 统计信息
	Author      PostAuthor `json:"author"`       // 作者信息
	IsLiked     bool       `json:"is_liked"`     // 是否已点赞
	IsCollected bool       `json:"is_collected"` // 是否已收藏
}

type PostDetailReq struct {
	PostId int64 `json:"post_id"` // 帖子ID
}

type PostDetailResp struct {
	Post PostDetail `json:"post"` // 帖子信息
}

type PostListReq struct {
	Page     int64  `json:"page"`      // 页码
	PageSize int64  `json:"page_size"` // 每页数量
	Theme    string `json:"theme"`     // 主题筛选
	UserId   int64  `json:"user_id"`   // 用户ID筛选
	Keyword  string `json:"keyword"`   // 关键词搜索
	SortBy   string `json:"sort_by"`   // 排序方式
}

type PostListResp struct {
	Posts    []PostDetail `json:"posts"`     // 帖子列表
	Total    int64        `json:"total"`     // 总数量
	Page     int64        `json:"page"`      // 当前页码
	PageSize int64        `json:"page_size"` // 每页数量
}

type PostStats struct {
	PostId       int64 `json:"post_id"`       // 帖子ID
	LikeCount    int64 `json:"like_count"`    // 点赞数
	ShareCount   int64 `json:"share_count"`   // 分享数
	ViewCount    int64 `json:"view_count"`    // 浏览数
	CollectCount int64 `json:"collect_count"` // 收藏数
}

type PostUpdateReq struct {
	PostId  int64  `json:"post_id"` // 帖子ID
	Title   string `json:"title"`   // 标题
	Content string `json:"content"` // 内容
	Images  string `json:"images"`  // 图片列表
	Theme   string `json:"theme"`   // 主题
	Tags    string `json:"tags"`    // 标签
	Status  int32  `json:"status"`  // 状态
}

type PostUpdateResp struct {
}
