// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: ai.proto

package ai

import (
	"context"

	"community/service/ai/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Agent            = __.Agent
	AgentChatConfig  = __.AgentChatConfig
	CreateAgentReq   = __.CreateAgentReq
	CreateAgentResp  = __.CreateAgentResp
	GetAgentListReq  = __.GetAgentListReq
	GetAgentListResp = __.GetAgentListResp
	KBSearchConfig   = __.KBSearchConfig
	ToolConfig       = __.ToolConfig
	WebSearchConfig  = __.WebSearchConfig

	Ai interface {
		CreateAgent(ctx context.Context, in *CreateAgentReq, opts ...grpc.CallOption) (*CreateAgentResp, error)
		GetAgentList(ctx context.Context, in *GetAgentListReq, opts ...grpc.CallOption) (*GetAgentListResp, error)
	}

	defaultAi struct {
		cli zrpc.Client
	}
)

func NewAi(cli zrpc.Client) Ai {
	return &defaultAi{
		cli: cli,
	}
}

func (m *defaultAi) CreateAgent(ctx context.Context, in *CreateAgentReq, opts ...grpc.CallOption) (*CreateAgentResp, error) {
	client := __.NewAiClient(m.cli.Conn())
	return client.CreateAgent(ctx, in, opts...)
}

func (m *defaultAi) GetAgentList(ctx context.Context, in *GetAgentListReq, opts ...grpc.CallOption) (*GetAgentListResp, error) {
	client := __.NewAiClient(m.cli.Conn())
	return client.GetAgentList(ctx, in, opts...)
}
