// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.0
// Source: ai.proto

package ai

import (
	"context"

	"community/service/ai/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	RunAgentReq     = __.RunAgentReq
	RunAgentResp    = __.RunAgentResp
	UpsertAgentReq  = __.UpsertAgentReq
	UpsertAgentResp = __.UpsertAgentResp

	Ai interface {
		UpsertAgent(ctx context.Context, in *UpsertAgentReq, opts ...grpc.CallOption) (*UpsertAgentResp, error)
		RunAgent(ctx context.Context, in *RunAgentReq, opts ...grpc.CallOption) (*RunAgentResp, error)
	}

	defaultAi struct {
		cli zrpc.Client
	}
)

func NewAi(cli zrpc.Client) Ai {
	return &defaultAi{
		cli: cli,
	}
}

func (m *defaultAi) UpsertAgent(ctx context.Context, in *UpsertAgentReq, opts ...grpc.CallOption) (*UpsertAgentResp, error) {
	client := __.NewAiClient(m.cli.Conn())
	return client.UpsertAgent(ctx, in, opts...)
}

func (m *defaultAi) RunAgent(ctx context.Context, in *RunAgentReq, opts ...grpc.CallOption) (*RunAgentResp, error) {
	client := __.NewAiClient(m.cli.Conn())
	return client.RunAgent(ctx, in, opts...)
}
